#!/bin/bash
#
# CleanUser - felhasználói adatok törlése
#
#


if [ -z $1 ]; then
    CLEANUSERFILE=".cleanuser"
    echo Alap működés.
else
    CLEANUSERFILE=".cleanusermedia"
    echo Média.
fi

cd /home

read -p "Komolyan? (i) " OK

if [ "$OK" == "i" ]; then
    echo "->"
    sleep 10
	ldir=`ls -A /home`
	for x in $ldir; do
		if [ -f "/home/$x/$CLEANUSERFILE" ]; then
		    mkdir "$x/.test" >>/dev/null 2>/dev/null
			for i in `cat "/home/$x/$CLEANUSERFILE"`; do
				echo "$x - $i"
				#
				# ÓVATOSAN !!!
				#
				cp -rf "$x/$i" "$x/.test"
			done
		fi
	done
fi

#
