#!/bin/bash
#
# CleanUser - felhasználói adatok törlése
#
#

CLEANUSERFILE=".cleanuser"

cd /home

read -p "Komolyan? (i) " OK

if [ "$OK" == "i" ]; then
	ldir=`ls -A /home`
	for x in $ldir; do
		if [ -f "/home/$x/$CLEANUSERFILE" ]; then
			for i in `cat "/home/$x/$CLEANUSERFILE"`; do
				echo "$x - $i"
				#
				# ÓVATOSAN !!!
				#
				rm -rf "$x/$i"
			done
		fi
	done
fi

#
