#!/bin/bash
#
# CleanUser - felhasználói adatok törlése
#
# Törlés
#

CLEANUSERFILE=".cleanuser"

cd /home

ldir=`ls -A /home`

for x in $ldir; do
	mkdir "$x/.test"
	if [ -f "/home/$x/$CLEANUSERFILE" ]; then
		for i in `cat "/home/$x/$CLEANUSERFILE"`; do
			echo "$x - $i"
			cp -r "$x/$i" "$x/.test"
		done
	fi
done

#
