#!/bin/bash
#
# video konvertálás
#
# feliratok kitörlése a fájlból
#

for i in *.mkv; do
	if [ -f "$i" ]; then
		mv "$i" orig-"$i" 2>/dev/null
		mkvmerge -o "$i" --no-subtitles orig-"$i" 2>/dev/null
		rm orig-"$i" 2>/dev/null
	else
		echo "Hiányzó fájl. ( $i )"
	fi
done

#
