#!/bin/bash
#
# KVM virtuális gép
#
# virtuális gép mentése
#

localdir=`dirname $0`
. $localdir/../vm-config

if [ -z $1 ]; then
  vname="$DEFAULT_VM"
else
  vname=$1
fi

run=`virsh list | grep $vname`
if [ -z $run]; then
	../runvm/vm-shutdown $vname
fi

if [ -d "$BACKUP_DIR" ]; then
	mkdir "$BACKUP_DIR"
fi

mkdir /$BACKUP_DIR/$vname 2>/dev/null

#virsh domblklist $vname > /$BACKUP_DIR/$vname/$vname.xml
virsh dumpxml $vname > /$BACKUP_DIR/$vname/$vname.xml

if [ -f /$BACKUP_DIR/$vname/$vname.qcow2 ]; then
	rm  /$BACKUP_DIR/$vname/$vname.qcow2 2>/dev/null
fi

cp /var/lib/libvirt/images/$vname.qcow2 /$BACKUP_DIR/$vname

if [ -z $run]; then
	../runvm/vm-start $vname
fi

#
