#!/bin/bash
#
# KVM virtuális gép
#
# virtuális gép mentése
#

localdir=`dirname $0`
. $localdir/../vm-config

if [ -z $1 ]; then
  vname="$DEFAULT_VM"
else
  vname=$1
fi

run=`virsh list | grep $vname`
if [ ! -z "$run" ]; then
	../runvm/vm-shutdown $vname >/dev/null 2>/dev/null
fi

if [ ! -d "$BACKUP_DIR" ]; then
	mkdir "$BACKUP_DIR" 2>/dev/null
fi

if [ ! -d "$BACKUP_DIR/$vname" ]; then
	mkdir "$BACKUP_DIR/$vname" 2>/dev/null
fi

if [ -f "$BACKUP_DIR/$vname/$vname.xml" ]; then
	rm "$BACKUP_DIR/$vname/$vname.xml" 2>/dev/null
fi

virsh dumpxml $vname > "$BACKUP_DIR/$vname/$vname.xml" 2>/dev/null

if [ -f "$BACKUP_DIR/$vname/$vname.qcow2" ]; then
	rm  "$BACKUP_DIR/$vname/$vname.qcow2" 2>/dev/null
fi

cp "/var/lib/libvirt/images/$vname.qcow2" "$BACKUP_DIR/$vname" 2>/dev/null

if [ ! -z "$run" ]; then
	../runvm/vm-start $vname >/dev6null 2>/dev/null
fi

#
