#!/bin/bash
#
# KVM virtuális gép
#
# virtuális gép pillanatkép készítése
#

localdir=`dirname $0`
. $localdir/../vm-config

if [ -z $1 ]; then
  vname="$DEFAULT_VM"
else
  vname=$1
fi

n=`date +%Y%m%d-%H%M`

if [ -z $2 ]; then
  sname="$n_$vname"
else
  sname=$2
fi

if [ -z $3 ]; then
  desc="$n"
else
  desc=$3
fi

virsh snapshot-create-as --domain $vname --name "$sname" --description "$desc"

#
