#!/bin/bash
#
# ssh client with tunnel
#

if [ -z "$1" ]; then
	killall sshpass
else
	pid=`cat $1`
	echo $pid
	if [ -z "$pid" ]; then
		killall sshpass
	else
		kill -9 $pid
		if [ "$?" == 0 ]; then
			rm "$1" 2&>>/dev/null
		fi
	fi
fi

#

