#!/bin/bash
#
# ssh client with tunnel
#

localdir=`dirname $0`
. $localdir/sshcl-config

#cd $BINDIR

sshpass -p "$TUN_PASSWORD" ssh -N -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" -R "$TUN_BRIDGE_PORT":localhost:22 "$TUN_USER"@"$TUN_SERVER" -p "$TUN_PORT" &

#cd TPATH

#

