#!/bin/bash
#
# ssh client with tunnel
#

# indítási könyvtár
TPATH=`pwd`

# adatok tárolója
LOGFILE="sshcl.log"

# kilépéskor az adatok megjelenítése: 0 - nem, 1 - igen
SHOW_LOGFILE=1

# a program helye
BINDIR="/usr/local/bin"

# tunnel szerver ipés port
TUN_SERVER="ka.hu"
TUN_SERVER_PORT="2222"

# tunnel szerver felhasználó
TUN_SERVER_USER="kauser"
TUN_SERVER_PASSWORD="Password1"

# tunnel átjáró port (a szerveren a két oldal között)
TUN_SERVER_BRIDGE_PORT="5000"

# tunnel-hez kapcsolódó port a helyi gépen
TUN_LOCAL_PORT="2222"

# tunnel-hez kapcsolódó port a távoli gépen
TUN_REMOTE_PORT="22"

# felasználó a cél gépen
TUN_CONNECT_USER="tunuser"

# pid-fájl kiterjesztés
PID_EXT=".pid"

# nyelvi elemek - language

#
