#!/bin/bash
#
# ssh client with tunnel
#

localdir=`dirname $0`
. $localdir/sshcl-config

#cd $BINDIR

sshpass -p "$TUN_SERVER_PASSWORD" \
	ssh -N -L "$TUN_LOCAL_PORT":localhost:"$TUN_SERVER_BRIDGE_PORT" \
	"$TUN_SERVER_USER"@"$TUN_SERVER" -p "$TUN_SERVER_PORT" &

#cd $TPATH

#
