#!/bin/bash
#
# ssh kliens tunnel-en
#

localdir=`dirname $0`
. $localdir/sshcl-config

#cd $BINDIR

list=`find sshcl-*$PID_EXT 2>/dev/null`
#echo $list
for i in $list; do
	pid=`cat $i`
	echo "$L_CLOSE_YES_W (PID: $pid)"
	kill -9 $pid 2&>>/dev/null
	if [ "$?" == 0 ]; then
		rm "$i" 2&>>/dev/null
	fi
done

#
