#!/bin/bash
#
# port átengedés ssh tunnel-en
#

localdir=`dirname $0`
. $localdir/webcl-init

list=`ls webcl-*$PID_EXT 2>>/dev/null`
if [ ! -z $list ]; then
	for i in $list; do
		pid=`cat $i`
		run=`ps -A | grep $pid | awk {'print $1'}`
		#echo "PID: $pid -> $run"
		if [ -z $run ]; then
			bifs=$IFS
			IFS="-"
			x=( $i )
			y=${x[1]}
			IFS="."
			x=( $y )
			y=${x[0]}
			IFS=$bifs
			srv=`sudo lsof -i -n | egrep '\<'$TUN_SERVER_SERVER'\>'`
			#echo $y - $srv
			if [ -z "$srv" ]; then
				$localdir/webcl-local-server $y
			fi
		fi
	done
else
	for x in ${!TUN_LOCAL_PORTS[@]}; do
		popen=`nmap localhost | grep ${TUN_LOCAL_PORTS[$x]}`
		if [ -z $popen ]; then
			$localdir/webcl-local-server ${TUN_REMOTE_PORTS[$x]}
		fi
	done
fi

#
