#!/bin/bash
#
# ssh client with tunnel
#

localdir=`dirname $0`
. $localdir/webhcl-config

#cd $BINDIR

if [ -z "$1" ]; then
	#killall sshpass
	echo
else
	pid=`cat $1`
	echo $pid
	if [ -z "$pid" ]; then
		#killall sshpass
		echo
	else
		kill -9 $pid
		if [ "$?" == 0 ]; then
			rm "$1"
		fi
	fi
fi

#cd $TPATH

#

