#!/bin/bash
#
# port átengedés ssh tunnel-en
#

localdir=`dirname $0`
. $localdir/webcl-init

if [ -z "$1" ]; then
	list=`find *$PID_EXT 2>/dev/null`
	if [ ! -z "$list" ]; then
		for i in $list; do
			pid=`cat $i`
			echo "PID: $pid"
			pkill -P $pid >>/dev/null 2>>/dev/null
			if [ "$?" == 0 ]; then
				rm "$i" 2&>>/dev/null
			fi
		done
	else
		pkill sshpass >>/dev/null 2>>/dev/null
	fi
else
	pid=`cat $1`
	echo $pid
	if [ -z "$pid" ]; then
		pkill sshpass
		echo -
	else
		pkill -P $pid >>/dev/null 2>>/dev/null
		if [ "$?" == 0 ]; then
			rm "$1" 2&>>/dev/null
		fi
	fi
fi

#
