#!/bin/bash
#
# port átengedés ssh tunnel-en
#

localdir=`dirname $0`
. $localdir/webcl-init

if [ -z "$1" ]; then
	list=`find webcl-*$PID_EXT 2>/dev/null`
	#echo $list
	for i in $list; do
		pid=`cat $i`
		echo "PID: $pid"
		kill -9 $pid 2&>>/dev/null
		if [ "$?" == 0 ]; then
			rm "$i" 2&>>/dev/null
		fi
	done
else
	pid=`cat $1`
	echo $pid
	if [ -z "$pid" ]; then
		killall sshpass 2&>>/dev/null
		killall autossh 2&>>/dev/null
		echo
	else
		kill -9 $pid
		if [ "$?" == 0 ]; then
			rm "$1" 2&>>/dev/null
		fi
	fi
fi

#
