#!/bin/bash
#
# ssh client with tunnel
#

# indítási könyvtár
TPATH=`pwd`

# adatok tárolója
LOGFILE="webcl.log"

# kilépéskor az adatok megjelenítése: 0 - nem, 1 - igen
SHOW_LOGFILE=1

# a program helye
BINDIR="/usr/local/bin"

# tunnel szerver
TUN_SERVER="ka.hu"
TUN_SERVER_PORT="2222"

# tunnel szerver felhasználó
TUN_SERVER_USER="ka"
TUN_SERVER_PASSWORD="Password0"

# tunnel átjáró port
TUN_SERVER_BRIDGE_PORTS=(5001 5002)

# tunnel-hez kapcsolódó port a távoli gépen
TUN_REMOTE_PORTS=(80 9090)

# tunnel-hez kapcsolódó port a helyi gépen
TUN_LOCAL_PORTS=(8080 8081)

# nyelvi elemek - language

#
