#!/bin/bash
#
# port átengedés ssh tunnel-en
#

localdir=`dirname $0`
. $localdir/webcl-config

if [ -z "$1" ]; then
	list=`ls webcl-*$PID_EXT`
	#echo $list
	for i in $list; do
		pid=`cat $i`
		echo "$L_CLOSE_YES_W (PID: $pid)"
		kill -9 $pid 2&>>/dev/null
		if [ "$?" == 0 ]; then
			rm "$i" 2&>>/dev/null
		fi
	done
else
	pid=`cat $1`
	echo $pid
	if [ -z "$pid" ]; then
		#killall sshpass
		echo
	else
		kill -9 $pid
		if [ "$?" == 0 ]; then
			rm "$1" 2&>>/dev/null
		fi
	fi
fi

#
