#!/bin/bash
#
# ssh client with tunnel
#

localdir=`dirname $0`
. $localdir/webcl-config

#cd $BINDIR

for i in ${!TUN_SERVER_BRIDGE_PORTS[@]}; do
	sshpass -p "$TUN_SERVER_PASSWORD" \
		ssh -N -L "${TUN_LOCAL_PORTS[$i]}":localhost:"${TUN_SERVER_BRIDGE_PORTS[$i]}" \
		"$TUN_SERVER_USER"@"$TUN_SERVER" -p "$TUN_SERVER_PORT" &
done

#cd $TPATH

#
