#!/bin/bash
#
# ssh client with tunnel
#

# indítási könyvtár
TPATH=`pwd`

# adatok tárolója
LOGFILE="webcl.log"

# kilépéskor az adatok megjelenítése: 0 - nem, 1 - igen
SHOW_LOGFILE=1

# a program helye
BINDIR="/usr/local/bin"

# tunnel szerver
TUN_SERVER="ka.hu"
TUN_SERVER_PORT="2222"

# tunnel szerver felhasználó
TUN_SERVER_USER="ka"
TUN_SERVER_PASSWORD="Password0"

# tunnel átjáró port
TUN_SERVER_BRIDGE_PORTS=(5001 5002)

# tunnel-hez kapcsolódó port a távoli gépen
TUN_REMOTE_PORTS=(22 9090)

# tunnel-hez kapcsolódó port a helyi gépen
TUN_LOCAL_PORTS=(8080 8081)

# pid-fájl kiterjesztés
PID_EXT=".pid"

# nyelvi elemek - language
L_CLOSE_TUNNEL="Kilép a kapcsolatból?"
L_CLOSE_SELECT="i/n"
L_CLOSE_YES="i"
L_CLOSE_NO="n"
L_CLOSE_YES_W="Igen"
L_CLOSE_NO_W="Nem"
L_OPEN_TUNNEL="Elindítja a kapcsolatot?"
L_OPEN_SELECT="i/n"
L_OPEN_YES="i"
L_OPEN_NO="n"
L_OPEN_YES_W="Igen"
L_OPEN_NO_W="Nem"

#
