#!/bin/bash
#
# port átengedés ssh tunnel-en
#

#cd /usr/local/bin

localdir=`dirname $0`
. $localdir/webcl-init

list=`ls webcl-*$PID_EXT 2>>/dev/null`
if [ ! -z $list ]; then
	for i in $list; do
		pid=`cat $i`
		run=`ps -A | grep $pid | awk {'print $1'}`
		#echo "PID: $pid -> $run"
		if [ -z "$run" ]; then
			bifs=$IFS
			IFS="-"
			x=( $i )
			y=${x[1]}
			IFS="."
			x=( $y )
			y=${x[0]}
			IFS=$bifs
			#echo $y
			$localdir/webcl-local-server $y
		fi
	done
else
	for x in ${!TUN_REMOTE_PORTS[@]}; do
		$localdir/webcl-local-server ${TUN_REMOTE_PORTS[$x]}
	done
fi

#
