#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése
#

d=`dirname $0`
. $d/backup-init

cd "$LOCALBACKUPDIR"

ldir=`ls -A /home`

EXCLTAR="--exclude=*.tar*"
EXCLBIGDIR="--exclude=*chrom*"

for x in $ldir; do
	for f in $USERDIRTOSAVE; do
		f2=`echo $f | tr -d '.'`
		if [ -d "/home/$x/$f/$EXCLUDEDIR" ]; then
    		if [ -f "$EXCLUDEDIR/$DEVICENAME-$x-$f2-arch.tar.gz" ]; then
			    rm "$EXCLUDEDIR/$DEVICENAME-$x-$f2-arch.tar.gz" 2>/dev/null
		    fi
	    	tar -rf "$EXCLUDEDIR/$DEVICENAME-$x-$f2-arch.tar" $EXCLBIGDIR "/home/$x/$f/$EXCLUDEDIR" 2>/dev/null >>"$LOGDIR/$LOGFILE"
    		gzip "./$EXCLUDEDIR/$DEVICENAME-$x-$f2-arch.tar" 2>/dev/null
		fi
	done
    if [ -f "/home/$x/$BACKUPDIRFILE" ]; then
    	for i in `cat "/home/$x/$BACKUPDIRFILE"`; do
    		i2=`echo "$i" | sed -r 's/[\/]+/-/g'`
    		if [ -d "/home/$x/$i2/$EXCLUDEDIR" ]; then
		    	if [ -f "$EXCLUDEDIR/$DEVICENAME-$x-$i2-arch.tar.gz" ]; then
			    	rm "$EXCLUDEDIR/$DEVICENAME-$x-$i2-arch.tar.gz" 2>/dev/null >/dev/null
    			fi
	    		tar -hrf "$EXCLUDEDIR/$DEVICENAME-$x-$i2-arch.tar" $EXCLBIGDIR "/home/$x/$i/$EXCLUDEDIR" 2>/dev/null >>"$LOGDIR/$LOGFILE"
		    	gzip -f "./$EXCLUDEDIR/$DEVICENAME-$x-$i2-arch.tar" 2>/dev/null
		    fi
		done
	fi
done

cd "$TPATH"

#
