#!/bin/bash
#
# SBackup - rendszer
#
# Beállítások, konfiguráció
#

# indítási könyvtár
TPATH=`pwd`

# modulok engedélyezése: 0 - letiltva, 1 - engedélyezve
ENABLE_SYSTEM=1
ENABLE_USER=1
ENABLE_DAYROTATE=1
ENABLE_LOG=1
ENABLE_MAIL=0
ENABLE_WEBDL=0
ENABLE_RCLONE=0
ENABLE_SQL=0
ENABLE_ENCODING=0
ENABLE_USB=0
ENABLE_WEBDIR=0
ENABLE_NETWORK=0

# archivum könyvtár (mentéből kimarad - backup-system-noexcl menti)
ARCHIVEDIR="_"

# mentés helye
LOCALBACKUPDIR="/usr/local/share/backup"

# a program helye
BINDIR="/usr/local/bin"

# szervernév, gépnév
# DEVICENAME="`hostname`"
DEVICENAME="0"

# logok
LOGDIR="/var/log"
LOGFILE="sbackup.log"
LOGARCHFILE="sbackup.log.1 sbackup.log.2 sbackup.log.3"

# log rotáció - a héten belüli nap száma: 1-7, 0 - letiltva
LOGROTATEDAY=5


# mentés előző napok
OLDDAY="d-1 d-2 d-3"

# mentésre jelölt könyvtárak
SYSDIRTOSAVE="/etc /var/www /usr/local/bin /var/lib/mysql"
USERDIRTOSAVE=".config .local Dokumentumok public_html"

# egyedi felhasználói könyvtárak $HOME könyvtárba
BACKUPDIRFILE=".backupdir"

# webszerver és ott lévő mentésfájlok
WEBDOWNLOAD="https://192.168.10.200/backup"
WEBFILES="pi-etc.tar.gz pi-sql.tar.gz pi-web.tar.gz pi-bin.tar.gz"

WEBBACKUPSITES="http://192.168.10.210/backup/griff-backup.tar http://192.168.10.88/1-backup.tar"

# minden webhelyről ezzel az azonosítóval próbál letölteni
WEBDLUSER="backup"
WEBDLPASSWD="backup"

# webszerver metéskönyvtára
WEBDIR="/var/www/html/backup"

# SQL adatbázisok helye
SQLDIR="/var/lib/mysql"

# rclone konfiguráció a felhős mentéshez
RCLONETARGET="google:/Mentés"

# USB-n lévő fájl neve, ha van ilyen, akkor arra megy a mentés
USBFILENAME=".backupusb"

# hálózati mentési hely SMB kapcsolathoz
NETHOST="192.168.0.1"
NETSHARE="Public"
NETDIR="Test"
NETUSER="terstuser"
NETPASSWORD="testpass"
NETTARGET="/mnt"

# modulok
PLUGINS=""

# kódolási jelszó
ENCODINGPASSPHARSE="titkosjelszo"

# alapbeállítások
EXCLUDEDIR=$ARCHIVEDIR

if [ "$DEVICENAME" = "" ]; then
	DEVICENAME="0"
fi

if [ ! -d "$LOCALBACKUPDIR" ]; then
	mkdir "$LOCALBACKUPDIR"
fi

if [ ! -d "$LOCALBACKUPDIR/$ARCHIVEDIR" ]; then
    mkdir "$LOCALBACKUPDIR/$ARCHIVEDIR"
fi

#
