#!/bin/bash
#
# SBackup - rendszer
#
# jelszavas védelem
#
#

d=`dirname $0`
. "$d/backup-init"

cd "$LOCALBACKUPDIR"

for b in *.tar.gz; do
	echo $b
	openssl enc -aes-256-cbc -d -in "$b" -out p-"$b" -k $ENCODINGPASSPHARSE >>/dev/null 2>>/dev/null
	rm "$b" >>/dev/null 2>>/dev/null
	mv p-"$b" "$b" >>/dev/null 2>>/dev/null
done

cd "$TPATH"

#
