#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
#echo "A szkript pontos könyvtára: $SCRIPT_DIR"

FILE_DIR=$(pwd)
#echo "A szkript pontos könyvtára: $FILE_DIR"

for file in *; do
  if [ -f "$file" ]; then
    echo $file
    cd "$SCRIPT_DIR"
    ./sbackup-enc-file "$FILE_DIR/$file"
    cd "$FILE_DIR"
    mv "$file" e-"$file"
  fi
done

#
