#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
#echo "A szkript pontos könyvtára: $SCRIPT_DIR"

FILE_DIR=$(pwd)
#echo "A szkript pontos könyvtára: $FILE_DIR"

if [ -f $1 ]; then
  echo $1
  cd $SCRIPT_DIR
  ./sbackup-enc-file $FILE_DIR/$1
  cd $FILE_DIR
  mv $1 e-$1
fi

#
