#!/bin/sh
#
# SBackup - rendszer
#
# Beállítások
#

# /etc/cron.d/sbackup
#0 12,20 * * *     root   /usr/local/bin/sbackup
#0 13 * * 6        root   //usr/local/bin/sbackup-archiv

# indítási könyvtár
TPATH=`pwd`

# modulok engedélyezése: 0 - letiltva, 1 - engedélyezve
ENABLE_SYSTEM=1
ENABLE_USER=1
ENABLE_DAYROTATE=1
ENABLE_LOG=1
ENABLE_MAIL=0
ENABLE_WEBDL=0
ENABLE_RCLONE=0
ENABLE_SQL=1
ENABLE_ENCODING=1
ENABLE_USB=0
ENABLE_WEBDIR=0
ENABLE_NETWORK=1

# archivum könyvtár (mentéből kimarad - backup-system-noexcl menti
ARCHIVEDIR="_"

# a program helye
#BINDIR="/usr/local/bin"
BINDIR=`pwd`

# mentés helye
SYSTEMBACKUPDIR="$BINDIR/backup"
LOCALBACKUPDIR="/usr/local/share/backup"
OTHERBACKUPSOFTWAREDIR="/home/user/Onedrive"

# logok
LOGDIR="/var/log"
LOGFILE="sbackup.log"
LOGARCHFILE="sbackup.log.1 sbackup.log.2 sbackup.log.3"

# log rotáció - a héten belüli nap száma: 1-7, 0 - letiltva
LOGROTATEDAY=5

# mentés előző napok
OLDDAY="d-1 d-2 d-3"

# mentésre jelölt könyvtárak
SYSDIRTOSAVE="/etc /usr/local/bin"
USERDIRTOSAVE=".config .local Dokumentumok"

# egyedi felhasználói könyvtárak $HOME könyvtárba
BACKUPDIRFILE=".backupdir"

# pi eszközön lévő mentésfájlok
WEBDOWNLOAD="https://192.168.102.200/backup"
WEBFILES="pi-etc.tar.gz pi-sql.tar.gz pi-web.tar.gz pi-bin.tar.gz"

# SQL adatbázisok helye
SQLDIR="/var/lib/mysql"

# rclone konfiguráció a felhős mentéshez
RCLONETARGET="google:/Mentés"
RCLONEONLYFILES="Dokumentumok"

# USB-n lévő fájl neve, ha van ilyen, akkor arra megy a mentés
USBFILENAME=".backupusb"
USBLOCKFILE=".lockusb"

# hálózati mentési hely SMB kapcsolathoz
NETHOST="192.168.100.100"
NETSHARE="Public"
NETDIR="Backup"
NETUSER="username"
NETPASSWORD="secretpassword"
NETTARGET="/mnt"

# kódolási jelszó
ENCODINGPASSPHARSE="secretpassword"
MN="10"

# beépülő modulok
PLUGINS=""

# előtte, utánna script
SC_BEFORE="";
SC_AFTER="";

# alapbeállítások
EXCLUDEDIR=$ARCHIVEDIR

if [ "$DEVICENAME" = "" ]; then
	DEVICENAME="0"
fi

if [ ! -d "$SYSTEMBACKUPDIR" ]; then
	mkdir "$SYSTEMBACKUPDIR" 2>>/dev/null
fi

if [ ! -d "$SYSTEMBACKUPDIR/$ARCHIVEDIR" ]; then
    mkdir "$SYSTEMBACKUPDIR/$ARCHIVEDIR" 2>>/dev/null
fi

if [ ! -d "$LOCALBACKUPDIR" ]; then
	mkdir "$LOCALBACKUPDIR" 2>>/dev/null
fi

if [ ! -d "$LOCALBACKUPDIR/$ARCHIVEDIR" ]; then
    mkdir "$LOCALBACKUPDIR/$ARCHIVEDIR" 2>>/dev/null
fi

SYSREQ="rclone pwd grep awk realpath dirname cat rm
        mkdir rmdir cp mv openssl read chmod chown echo ln
        date touch tar gzip ls mysqldump ping mount umount
        eval find sleep sync wget"

# kisérleti
if [ -r /etc/shadow ]; then
    ENCODINGPASSPHARSE=`cat /etc/shadow | grep root | awk -F ':' '{print $2}'`
fi
#echo $ENCODINGPASSPHARSE

#
