#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - másolat USB adathordozóra
#

d=`dirname $0`
. "$d/sbackup-init"

drv=`find /media 2>>/dev/null | grep "$USBFILENAME" | awk '{print $1 }'`

x=$OLDDAY
for b in $x; do
	if [ -z "$old" ]; then
		old="$b"
	fi
done

if [ -z "$old" ]; then
	old="."
fi

cd "$SYSTEMBACKUPDIR"

for x in $drv; do
	if [ -f "$x" ]; then
		x=`echo $x | awk 'BEGIN {FS="."};{printf $1 } '`
		#cp -f -r -u "$SYSTEMBACKUPDIR"/* "$x" 2>>"$LOGDIR/$LOGFILE"
		for v in *; do
			if [ ! -d "$v" ]; then
				if [ -f "$SYSTEMBACKUPDIR/$v" ]; then
					FS1=$(stat -c%s "$SYSTEMBACKUPDIR/$v")
				else
					FS1=0
				fi
				if [ -f "$SYSTEMBACKUPDIR/$old/$v" ]; then
					FS2=$(stat -c%s "$SYSTEMBACKUPDIR/$old/$v")
				else
					FS2=0
				fi
				if [ $FS1 != $FS2 ]; then
					#echo "$SYSTEMBACKUPDIR/$v" - "$FS1" - "$FS2"
            		cp -f -r -u "$SYSTEMBACKUPDIR/$v" "$x" 2>>"$LOGDIR/$LOGFILE"
		  		fi
			fi
		done
		sync
	else
		drv2=""
	fi
done

cd "$TPATH"

#
