#!/bin/bash
#
# SBackup - rendszer
#
# jelszavas védelem
#
#

. "./sbackup-init"

if [ -n "$1" ]; then
	echo $1
	openssl aes-256-cbc -salt -a -d -in "$1" -out "p-$1" -iter "$MN" -k "$ENCODINGPASSPHARSE" #>>/dev/null 2>>/dev/null
	#openssl enc -aes-256-cbc -d -in "$1" -out p-"$b" -k $ENCODINGPASSPHARSE #>>/dev/null 2>>/dev/null
	rm "$1" >>/dev/null 2>>/dev/null
	mv p-"$1" "$1" >>/dev/null 2>>/dev/null
fi

#
