#!/bin/bash
#
# SBackup - rendszer
#
# Mentések rotációja
#
#

. "./sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

for b in $OLDDAY; do
	c="$b $c"
done
for b in $c; do
	if [ -z "$n" ]; then
		if [ -d "$b" ]; then
			rm "$b"/*.tar* 2>/dev/null
		else
			mkdir "$b" 2>/dev/null
		fi
	else
		if [ -d "$n" ]; then
			rm "$n"/*.tar* 2>/dev/null
		else
			mkdir "$n" 2>/dev/null
		fi
		mv -u -f "$b"/*.tar* "$n" 2>/dev/null
	fi
	n="$b"
done
if [ -d "$b" ]; then
	rm "$b"/*.tar* 2>/dev/null
else
	mkdir "$b" 2>/dev/null
fi
mv -u -f *.tar* "$b" 2>/dev/null

if [ ! -z $LOCALBACKUPDIR ]; then
    cp -f -r -u "$SYSTEMBACKUPDIR"/* "$LOCALBACKUPDIR" 2>>"$LOGDIR/$LOGFILE"
fi

#
