#!/bin/bash
#
# SBackup - rendszer
#
# indítás
#

TPATH=`pwd`

if [ ! -f "$TPATH/sbackup-starter" ]; then
  localdir=`realpath $0`
  if [ ! -f "$localdir/sbackup-starter" ]; then
    localdir=${localdir%/*}
  fi
  cd $localdir
fi

. ./sbackup-starter

cd $TPATH

#
