#!/bin/bash
#
# SBackup - rendszer
#
# jelszavas védelem
#
#

d=`dirname $0`
. "$d/sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

for b in *.tar.gz; do
	#echo $b
	openssl aes-256-cbc -salt -a -d -in "$b" -out "p-$b" -iter "$MN" -k "$ENCODINGPASSPHARSE" >>/dev/null 2>>/dev/null
	#openssl enc -aes-256-cbc -d -in "$b" -out p-"$b" -k $ENCODINGPASSPHARSE #>>/dev/null 2>>/dev/null
	rm "$b" >>/dev/null 2>>/dev/null
	mv p-"$b" "$b" >>/dev/null 2>>/dev/null
done

cd "$TPATH"

#
