#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - mentés másolása web-szerver alá
#

startdir=`dirname $0`
. "./sbackup-init"

cd "$SYSTEMBACKUPDIR"

if [ -d "$WEBDIR" ]; then
	rm "/$WEBDIR/$DEVICENAME-backup.tar" 2>/dev/null
	tar rf "/$WEBDIR/$DEVICENAME-backup.tar" *.tar.gz 2>/dev/null >>"$LOGDIR/$LOGFILE"
fi

cd "$startdir"

#
