#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - USB eszköz keresése, adatok mentése
#

. "./sbackup-init"

s=`cat /proc/partitions | grep nvme `

if [ -z "$s" ]; then
  e=`cat /proc/partitions | grep sd | awk '{print $4}' | grep -v sda | grep  [123456789] `
else
  e=`cat /proc/partitions | grep sd | awk '{print $4}' | grep  [123456789] `
fi


for x in $e; do
	mkdir "/media/$x" >/dev/null 2>>"$LOGDIR/$LOGFILE"
	/bin/mount "/dev/$x" "/media/$x" 2>/dev/null #2>>"$LOGDIR/$LOGFILE"
done

./sbackup-usb-copy $1
#sleep 10
#sync

for x in $e; do
	/bin/umount "/media/$x" >/dev/null 2>/dev/null 2>>"$LOGDIR/$LOGFILE"
	rmdir "/media/$x" >/dev/null 2>>"$LOGDIR/$LOGFILE"
done

#
