#!/bin/bash
#
# SBackup - MySQL/MariaDB
#
# Adatbázisok mentése
#
#

. "./sbackup-config"

bs=`command -v mariadb-backup`

if [ -n "$bs" ]; then
  ./sbackup-denc-file "$DEVICENAME-sql-bakup.tar.gz" "$SYSTEMBACKUPDIR" 2>/dev/null
  tar xvfz "$SYSTEMBACKUPDIR/$DEVICENAME-sql-backup.tar.gz" #2>/dev/null
  service mariadb stop
  rm -R /var/lib/mysql/*
  mariadb-backup --prepare --target-dir=/var/lib/mysql-backup/ #2>>/dev/null
  mariadb-backup --copy-back --target-dir=/var/lib/mysql-backup/ #2>>/dev/null
  chown -R mysql:mysql /var/lib/mysql/
  service mariadb start
else
  ./sbackup-denc-file "$DEVICENAME-sql.tar.gz" "$SYSTEMBACKUPDIR" 2>/dev/null
  tar xvfz "$SYSTEMBACKUPDIR/$DEVICENAME-sql.tar.gz" #2>/dev/null
  mariadb <*.sql
  rm *.sql
fi


#
