#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése
#

d=`dirname $0`
. $d/sbackup-init

cd "$LOCALBACKUPDIR"

ldir=`ls -A /home`

EXCLTAR="--exclude=*.tar*"
EXCLBIGDIR="--exclude=*chrom*"

for f in $SYSDIRTOSAVE; do
	f2=`basename "$f"`
	if [ -f "$DEVICENAME-system-$f2-noexcl.tar.gz" ]; then
		rm "$DEVICENAME-system-$f2-noexcl.tar.gz" 2>/dev/null
	fi
	tar rf "$DEVICENAME-system-$f2-noexcl.tar" $EXCLTAR $f 2>/dev/null >>"$LOGDIR/$LOGFILE"
	gzip "./$DEVICENAME-system-$f2-noexcl.tar" 2>/dev/null
done

if [ "$ENABLE_USER" = 1 ]; then
	for x in $ldir; do
		for f in $USERDIRTOSAVE; do
			f2=`echo $f | tr -d '.'`
			if [ -f "$DEVICENAME-$x-$f2-noexcl.tar.gz" ]; then
				rm "$DEVICENAME-$x-$f2-noexcl.tar.gz" 2>/dev/null
			fi
			tar -rf "$DEVICENAME-$x-$f2-noexcl.tar" $EXCLBIGDIR "/home/$x/$f" 2>/dev/null >>"$LOGDIR/$LOGFILE"
			gzip "./$DEVICENAME-$x-$f2-noexcl.tar" 2>/dev/null
		done
		if [ -f "/home/$x/$BACKUPDIRFILE" ]; then
			for i in `cat "/home/$x/$BACKUPDIRFILE"`; do
				i2=`echo "$i" | sed -r 's/[\/]+/-/g'`
				if [ -f "$DEVICENAME-$x-$i2-noexcl.tar.gz" ]; then
					rm "$DEVICENAME-$x-$i2-noexcl.tar.gz" 2>/dev/null >/dev/null
				fi
				tar -hrf "$DEVICENAME-$x-$i2-noexcl.tar" $EXCLBIGDIR "/home/$x/$i" 2>/dev/null >>"$LOGDIR/$LOGFILE"
				gzip -f "./$DEVICENAME-$x-$i2-noexcl.tar" 2>/dev/null
			done
		fi
	done
fi

cd "$TPATH"

#
