#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - mentés hálózati meghajtóra
#

startdir=`dirname $0`
. "./sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

x=$OLDDAY
for b in $x; do
	if [ -z "$old" ]; then
		old="$b"
	fi
done

if [ -z "$old" ]; then
	old="."
fi

if ping -c 1 -W 1 "$NETHOST" >>/dev/null; then
	#echo "$NETHOST" létezik
	mount -t cifs "//$NETHOST/$NETSHARE" "$NETTARGET" -o rw,username="$NETUSER",password="$NETPASSWORD" 2>>"$LOGDIR/$LOGFILE"

	if [ -d "$NETTARGET" ]; then
		d=`date`
		#cd $NETTARGET/$NETDIR
	else
		d=`date`
		mkdir $NETTARGET 2>>/dev/null
	fi

    for v in *; do
	    if [ ! -d "$v" ]; then
            if [ ! -z $1 ]; then
                f1="$SYSTEMBACKUPDIR/$ARCHIVEDIR"
                f2="$SYSTEMBACKUPDIR/$ARCHIVEDIR/$old"
            else
                f1="$SYSTEMBACKUPDIR"
                f2="$SYSTEMBACKUPDIR/$old"
            fi
        	if [ -f "$f1/$v" ]; then
        		FS1=$(stat -c%s "$f1/$v")
        	else
        		FS1=0
        	fi
        	if [ -f "$f2/$v" ]; then
        		FS2=$(stat -c%s "$f2/$v")
        	else
        		FS2=0
        	fi
  			  #echo $f1/$v $FS1 $FS2
  			if [ $FS1 != $FS2 ]; then
            	cp -f -r -u "$f1/$v" "$NETTARGET/$NETDIR" 2>>"$LOGDIR/$LOGFILE"
        	fi
        fi
    done

	umount "$NETTARGET" 2>>"$LOGDIR/$LOGFILE"
else
	echo "$NETHOST" nem elérhető. 2>>"$LOGDIR/$LOGFILE"
fi

cd $startdir

#
