#!/bin/bash
#
# SBackup - rendszer
#
# telepítő
#

DESTDIR="/opt/sbackup"

ID=`id -u`
if [ $ID = 0 ]; then
    echo
    read -e -p "Telepítés helye (alap: $DESTDIR): " -i "$DESTDIR" DD
    DESTDIR=${DESTDIR:-/opt/sbackup}
    echo
    echo Másolás: $DESTDIR
    mkdir -p "$DESTDIR"
    if [ -e $DESDIR ]; then
	    if [ -e "$DESTDIR/sbackup-config" ]; then
		    mv -f "$DESTDIR/sbackup-config" "$DESTDIR/sbackup-config-old"
	    fi
        cp sbackup* "$DESTDIR"
	    chmod 700 "$DESTDIR/sbackup-config"
	    #chown root:root "$DESTDIR/sbackup-config"
	    chown root:root *
        echo
        echo Indítófájlok létrehozása: "$DESTDIR/sbackup"
        echo Indítófájlok létrehozása: "$DESTDIR/sbackup-archive"
        echo
        echo Linkek létrehozása.
        if [ -e "/usr/local/bin/sbackup" ]; then
          mv -f "/usr/local/bin/sbackup" "/usr/local/bin/sbackup-old"
        fi
        ln -s "$DESTDIR/sbackup" /usr/local/bin/sbackup
        if [ -e "/usr/local/bin/sbackup-archive" ]; then
          mv -f "/usr/local/bin/sbackup-archive" "/usr/local/bin/sbackup-archive-old"
        fi
        ln -s "$DESTDIR/sbackup-archive" /usr/local/bin/sbackup-archive
        echo
        echo Telepítés kész.
        echo
        echo Indítás: $DESTDIR/sbackup vagy sbackup
        echo Indítás: $DESTDIR/sbackup-archive vagy sbackup-archive
        echo
        echo További beállítások: "$DESTDIR"/sbackup-config
        echo Kérem ellenőrizze a beállításokat és hangolja a mentést a rendszeréhez.
        echo
        echo A programkörnyezet ellenőrzése:
        ./sbackup-check
        if [ ! -f /etc/cron.d/sbackup ]; then
	        echo "# /etc/cron.d/sbackup" >/etc/cron.d/sbackup
			echo "" >>/etc/cron.d/sbackup
			echo "0 12,15,20 * * *     root   /usr/local/bin/sbackup" >>/etc/cron.d/sbackup
			echo "0 13 * * 5,6        root   //usr/local/bin/sbackup-archiv" >>/etc/cron.d/sbackup
			echo "#" >>/etc/cron.d/sbackup
			echo "" >>/etc/cron.d/sbackup
	        echo /cron.d/sbackup létrehozva, kérem elenőrizze és állítsa be a mentés idejét.
	        echo
        fi
    else
        echo
        echo Telepítési hiba. Célkönyvtár létrehozási/elérési hiba.
        echo
        echo Ellenőrizze a jogosultságokat és próbálja újra.
        echo
    fi
else
    echo
    echo Nincs elég jogosultság a telepítéshez. A telepítéshez \"root\" jogosultság szükséges.
    echo Ellenőrizze a jogosultságokat és próbálja újra.
    echo
fi

#
