#!/bin/bash
#
# SBackup - rendszer
#
# jelszavas védelem
#
#

. "./sbackup-init"

if [ -n "$1" ]; then
	echo $1
	#openssl enc -aes-256-cbc -d -in "$1" -out p-"$b" -k $ENCODINGPASSPHARSE #>>/dev/null 2>>/dev/null
	openssl aes-256-cbc -salt -a -d -in "$1" -out "$1"-p -iter "$MN" -k "$ENCODINGPASSPHARSE" #>>/dev/null 2>>/dev/null
	if [ $? -eq 0 ]; then
	  rm "$1" >>/dev/null 2>>/dev/null
	  mv "$1"-p "$1" >>/dev/null 2>>/dev/null
	fi
fi

#
