#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése
#

d=`dirname $0`
. $d/sbackup-init

if [ ! -d "$LOCALBACKUPDIR/$EXCLUDEDIR" ]; then
	mkdir "$LOCALBACKUPDIR/$EXCLUDEDIR"
fi
cd "$LOCALBACKUPDIR/$EXCLUDEDIR"

ldir=`ls -A /home`

EXCLTAR="--exclude=*.tar*"
EXCLBIGDIR="--exclude=*chrom*"

for x in $ldir; do
    for f in $USERDIRTOSAVE; do
	f2=`echo $f | tr -d '.'`
	if [ -d "/home/$x/$f/$EXCLUDEDIR" ]; then
    	    if [ -f "$DEVICENAME-$x-$f2-arch.tar.gz" ]; then
	        rm "$$DEVICENAME-$x-$f2-arch.tar.gz" 2>/dev/null
	    fi
	    tar -rf "$DEVICENAME-$x-$f2-arch.tar" $EXCLBIGDIR "/home/$x/$f/$EXCLUDEDIR" 2>/dev/null >>"$LOGDIR/$LOGFILE"
    	    gzip "./$DEVICENAME-$x-$f2-arch.tar" 2>/dev/null
	fi
    done
    if [ -f "/home/$x/$BACKUPDIRFILE" ]; then
    	for i in `cat "/home/$x/$BACKUPDIRFILE"`; do
    	    i2=`echo "$i" | sed -r 's/[\/]+/-/g'`
    	    if [ -d "/home/$x/$i2/$EXCLUDEDIR" ]; then
	    	if [ -f "$DEVICENAME-$x-$i2-arch.tar.gz" ]; then
	        	rm "$DEVICENAME-$x-$i2-arch.tar.gz" 2>/dev/null >/dev/null
    		fi
		tar -hrf "$DEVICENAME-$x-$i2-arch.tar" $EXCLBIGDIR "/home/$x/$i/$EXCLUDEDIR" 2>/dev/null >>"$LOGDIR/$LOGFILE"
		gzip -f "./$DEVICENAME-$x-$i2-arch.tar" 2>/dev/null
	    fi
	done
    fi
done

cd "$TPATH"

#
