#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése
#

d=`dirname $0`
. "$d/sbackup-init"

d=`date`
echo "$d Mentés elkezdése." >> "$LOGDIR/$LOGFILE"

eval $SC_BEFORE

# log rotáció
if [ "$ENABLE_LOG" = 1 ]; then
		d=`date`
		./sbackup-log 2>/dev/null
		echo "$d Log rotáció." >> "$LOGDIR/$LOGFILE"
fi

# napi mentés rotáció
if [ "$ENABLE_DAYROTATE" = 1 ]; then
		d=`date`
		echo "$d Napi mentés rotáció." >> "$LOGDIR/$LOGFILE"
		./sbackup-dayrotate 2>/dev/null
fi

# helyi gép
if [ "$ENABLE_SYSTEM" = 1 ]; then
		d=`date`
		echo "$d Helyi gép mentése." >> "$LOGDIR/$LOGFILE"
		./sbackup-system 2>/dev/null
fi

# egyéb WEB forrás
if [ "$ENABLE_WEBDL" = 1 ]; then
		d=`date`
		echo "$d Távoli gép weboldalról mentése." >> "$LOGDIR/$LOGFILE"
		./sbackup-webdl 2>/dev/null
fi

# levelezés
if [ "$ENABLE_MAIL" = 1 ]; then
		d=`date`
		echo "$d Levelezés könyvtárainak mentése." >> "$LOGDIR/$LOGFILE"
		./sbackup-mail 2>/dev/null
fi

# sql
if [ "$ENABLE_SQL" = 1 ]; then
		d=`date`
		echo "$d SQL adatbázisok mentése." >> "$LOGDIR/$LOGFILE"
		./sbackup-sql 2>>/dev/null
fi

# jelszavas védelem
if [ "$ENABLE_ENCODING" = 1 ]; then
		d=`date`
		echo "$d Jelszavas védelem." >> "$LOGDIR/$LOGFILE"
		./sbackup-enc 2>/dev/null
fi

# mentés felhőbe, adathordozóra
if [ "$ENABLE_USB" = 1 ]; then
		d=`date`
		echo "$d Mentés USB adathordozóra." >> "$LOGDIR/$LOGFILE"
		./sbackup-usb-mount 2>/dev/null
fi

if [ "$ENABLE_RCLONE" = 1 ]; then
		d=`date`
		echo "$d Mentés felhőbe." >> "$LOGDIR/$LOGFILE"
		./sbackup-rclone 2>/dev/null
fi

# mentés hálózati meghajtóra
if [ "$ENABLE_NETWORK" = 1 ]; then
		d=`date`
		echo "$d Mentés hálózati meghajtóra." >> "$LOGDIR/$LOGFILE"
		./sbackup-net-copy 2>/dev/null
fi

# mentés web könyvtárba
if [ "$ENABLE_WEBDIR" = 1 ]; then
		d=`date`
		echo "$d Mentés web könyvtárba." >> "$LOGDIR/$LOGFILE"
		./sbackup-webdir 2>/dev/null
fi

# beépülő modulok
for i in $PLUGINS; do
	if [ -f "$i" ]; then
		. ./"$i" >> "$LOGDIR/$LOGFILE"
	fi
done

eval $SC_AFTER

d=`date`
echo "$d Kész." >> "$LOGDIR/$LOGFILE"

#
