#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - másolat USB adathordozóra
#

startdir=`dirname $0`
. "./sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

drv=`find /media 2>>/dev/null | grep "$USBFILENAME" | awk '{print $1 }'`

x=$OLDDAY
for b in $x; do
	if [ -z "$old" ]; then
		old="$b"
	fi
done

if [ -z "$old" ]; then
	old="."
fi

for x in $drv; do
	if [ -f "$x" ]; then
		x=`echo $x | awk 'BEGIN {FS="."};{printf $1 } '`
		#cp -f -r -u "$SYSTEMBACKUPDIR"/* "$x" 2>>"$LOGDIR/$LOGFILE"
		for v in *; do
			if [ ! -d "$v" ]; then
				if [ -f "$SYSTEMBACKUPDIR/$v" ]; then
					FS1=$(stat -c%s "$SYSTEMBACKUPDIR/$v")
				else
					FS1=0
				fi
				if [ -f "$SYSTEMBACKUPDIR/$old/$v" ]; then
					FS2=$(stat -c%s "$SYSTEMBACKUPDIR/$old/$v")
				else
					FS2=0
				fi
				#echo $SYSTEMBACKUPDIR/$v $FS1 $FS2
				if [ $FS1 != $FS2 ]; then
					#echo "$x/$v" - "$FS1" - "$FS2"
                    if [ ! -z $1 ]; then
                		cp -f -r -u "$SYSTEMBACKUPDIR/$ARCHIVEDIR/$v" "$x/$ARCHIVEDIR" 2>>"$LOGDIR/$LOGFILE"
                    else
                		cp -f -r -u "$SYSTEMBACKUPDIR/$v" "$x" 2>>"$LOGDIR/$LOGFILE"
                    fi
		  		fi
			fi
		done
		sync
	else
		drv2=""
	fi
done

cd $startdir

#
