#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - másolat egyéb szoftver részére
#

startdir=`dirname $0`
. "./sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

cd $startdir

#
