#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - rclone gdrive-ba
#

startdir=`dirname $0`
. "./sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

x=$OLDDAY
for b in $x; do
	if [ -z "$old" ]; then
		old="$b"
	fi
done

if [ -z "$old" ]; then
	old="."
fi

for v in *; do
	if [ ! -d "$v" ]; then
        if [ ! -z $1 ]; then
            f1="$SYSTEMBACKUPDIR/$ARCHIVEDIR"
            f2="$SYSTEMBACKUPDIR/$ARCHIVEDIR/$old"
        else
            f1="$SYSTEMBACKUPDIR"
            f2="$SYSTEMBACKUPDIR/$old"
        fi
		if [ -f "$f1/$v" ]; then
			FS1=$(stat -c%s "$f1/$v")
		else
			FS1=0
		fi
		if [ -f "$f2/$v" ]; then
			FS2=$(stat -c%s "$f2/$v")
		else
			FS2=0
		fi
		if [ $FS1 != $FS2 ]; then
			#echo "$f1/$v" - "$FS1" - "$FS2"
        	if [ -z "$RCLONEONLYFILES" ]; then
          	  rclone copy "$f1/$v" "$RCLONETARGET" >>"$LOGDIR/$LOGFILE" 2>/dev/null
			else
			  for e in $RCLONEONLYFILES; do
			    if [[ "$v" == *"$e"* ]]; then
				    #echo "$f1/$v" "$RCLONETARGET"
          		    rclone copy "$f1/$v" "$RCLONETARGET" >>"$LOGDIR/$LOGFILE" 2>/dev/null
          	    fi
          	  done
        	fi
  		fi
	fi
done

cd $startdir

#
