#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - rclone gdrive-ba
#

startdir=`dirname $0`
. "./sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

x=$OLDDAY
for b in $x; do
	if [ -z "$old" ]; then
		old="$b"
	fi
done

if [ -z "$old" ]; then
	old="."
fi

for v in *; do
	if [ ! -d "$v" ]; then
		if [ -f "$SYSTEMBACKUPDIR/$v" ]; then
			FS1=$(stat -c%s "$SYSTEMBACKUPDIR/$v")
		else
			FS1=0
		fi
		if [ -f "$SYSTEMBACKUPDIR/$old/$v" ]; then
			FS2=$(stat -c%s "$SYSTEMBACKUPDIR/$old/$v")
		else
			FS2=0
		fi
		if [ $FS1 != $FS2 ]; then
			#echo "$SYSTEMBACKUPDIR/$v" - "$FS1" - "$FS2"
            if [ ! -z $1 ]; then
        	    if [ -z "$RCLONEONLYFILES" ]; then
          		    rclone copy "$SYSTEMBACKUPDIR/$ARCHIVEDIR/$v" "$RCLONETARGET" >>"$LOGDIR/$LOGFILE" 2>/dev/null
		    	else
			    	for e in $RCLONEONLYFILES; do
				    	if [[ "$v" == *"$e"* ]]; then
					    	#echo "$SYSTEMBACKUPDIR/$v" "$RCLONETARGET"
          				    rclone copy "$SYSTEMBACKUPDIR/$ARCHIVEDIR/$v" "$RCLONETARGET" >>"$LOGDIR/$LOGFILE" 2>/dev/null
          		    	fi
          		    done
        	    fi
            else
        	    if [ -z "$RCLONEONLYFILES" ]; then
          		    rclone copy "$SYSTEMBACKUPDIR/$v" "$RCLONETARGET" >>"$LOGDIR/$LOGFILE" 2>/dev/null
			    else
				    for e in $RCLONEONLYFILES; do
					    if [[ "$v" == *"$e"* ]]; then
						    #echo "$SYSTEMBACKUPDIR/$v" "$RCLONETARGET"
          				    rclone copy "$SYSTEMBACKUPDIR/$v" "$RCLONETARGET" >>"$LOGDIR/$LOGFILE" 2>/dev/null
          			    fi
          		    done
                fi
        	fi
  		fi
	fi
done

cd $startdir

#
