#!/bin/sh
#
# SBackup - MySQL/MariaDB
#
# Adatbázisokp mentése:
#
#

ut=`pwd`
#cd /usr/local/share/sbackup 2>>/var/log/sbackup.log

mysqldump --all-databases >./mysqldb.sql #2>>/var/log/sbackup.log
tar cvvfz "sql.tar.gz" *.sql #2>/dev/null >>"$LOGDIR/$LOGFILE"
rm *.sql

cd $ut

#
