#!/bin/bash
#
# SBackup - rendszer
#
# jelszavas védelem
#
#

. "./sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

for b in *.tar.gz; do
	#echo $b
	#openssl enc -aes-256-cbc -in "$b" -out p-"$b" -k $ENCODINGPASSPHARSE >>/dev/null 2>>/dev/null
	openssl aes-256-cbc -salt -a -e -in "$b" -out "$b"-p -iter "$MN" -k "$ENCODINGPASSPHARSE" >>/dev/null 2>>/dev/null
	if [ $? -eq 0 ]; then
	  rm "$b" >>/dev/null 2>>/dev/null
	  mv "$b"-p "$b" >>/dev/null 2>>/dev/null
	fi
done

#
