#!/bin/bash
#
# SBackup - rendszer
#
# Adatbázisok mentése
#
#

startdir=`dirname $0`
. "./sbackup-init"

cd "$SYSTEMBACKUPDIR"

if [ -d "$SQLDIR" ]; then
	if [ -f "$DEVICENAME-sql.tar.gz" ]; then
		rm "$DEVICENAME-sql.tar.gz" 2>>/dev/null
	fi

    bs=`command -v mariadb-backup`
    if [ -n "$bs" ]; then
      rm -R /var/lib/mysql-backup/* >>/var/lib/mysql-backup/mdbbackup.log 2>>/dev/null
      if [ ! -n "$SQL_USER" ]; then
        SQL_USER="root"
      fi
      $bs --backup --target-dir=/var/lib/mysql-backup/ --user="$SQL_USER" --password="$SQL_PASSWORD" 2>>/dev/null
      tar cvvfz "$SYSTEMBACKUPDIR/$DEVICENAME-sql-bakup.tar.gz" /var/lib/mysql-backup/ 2>/dev/null >>"$LOGDIR/$LOGFILE"
    else
	  # egyszrre az összes adatbázis:
	  # mysqldump --all-databases >./mysqldb.sql #2>>/var/log/sbackup.log
	  #
	  # vagy
	  #
	  # egyessével az adatbázisok:
	  for x in "$SQLDIR"/*; do
	    if [ -d "$x" ]; then
		  y="${x##*/}"
		  if [ "$y" != "performance_schema" ]; then
			mysqldump "$y" >"sqldb-$y.sql" 2>>"$LOGDIR/$LOGFILE"
		  fi
	    fi
	  done

	  # tömörítés
	  tar cvvfz "$DEVICENAME-sql.tar.gz" *.sql 2>/dev/null >>"$LOGDIR/$LOGFILE"
	  rm *.sql 2>/dev/null
    fi
fi

cd "$startdir"

#

