#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - másolat USB adathordozóra
#

startdir=`dirname $0`
. "./sbackup-init"

if [ ! -z $1 ]; then
    cd "$SYSTEMBACKUPDIR/$ARCHIVEDIR"
else
    cd "$SYSTEMBACKUPDIR"
fi

drv=`find /media 2>>/dev/null | grep "$USBFILENAME" | awk '{print $1 }'`

x=$OLDDAY
for b in $x; do
	if [ -z "$old" ]; then
		old="$b"
	fi
done

if [ -z "$old" ]; then
	old="."
fi

for x in $drv; do
	if [ -f "$x" ]; then
		x=`echo $x | awk 'BEGIN {FS="."};{printf $1 } '`
        if [ ! -z $1 ]; then
            f1="$SYSTEMBACKUPDIR/$ARCHIVEDIR"
            f2="$SYSTEMBACKUPDIR/$ARCHIVEDIR/$old"
        else
            f1="$SYSTEMBACKUPDIR"
            f2="$SYSTEMBACKUPDIR/$old"
        fi
		for v in *; do
			if [ ! -d "$v" ]; then
				if [ -f "$f1/$v" ]; then
					FS1=$(stat -c%s "$f1/$v")
				else
					FS1=0
				fi
				if [ -f "$f2/$v" ]; then
					FS2=$(stat -c%s "$f2/$v")
				else
					FS2=0
				fi
				#echo $f1/$v $FS1 $FS2
				if [ $FS1 != $FS2 ]; then
              		cp -f -r -u "$f1/$v" "$x" 2>>"$LOGDIR/$LOGFILE"
		  		fi
			fi
		done
		sync
	else
		drv2=""
	fi
done

cd $startdir

#
