#!/bin/bash
#
# SBackup - rendszer
#
# Adatbázisok mentése
#
#

startdir=`dirname $0`
. "./sbackup-init"

cd "$SYSTEMBACKUPDIR"

if [ -d "$SQLDIR" ]; then
	if [ -f "$DEVICENAME-sql.tar.gz" ]; then
		rm "$DEVICENAME-sql.tar.gz" 2>>/dev/null
	fi

	# egyszrre az összes adatbázis
	# mysqldump --all-databases >sqldb-all.sql 2>>$LOGFILE
	#
	# egyessével az adatbázisok:
	# mysqldump mysql > mysql.sql
	# mysqldump phpmyadmin> phpmyadmin.sql
	for x in "$SQLDIR"/*; do
	if [ -d "$x" ]; then
		y="${x##*/}"
		if [ "$y" != "performance_schema" ]; then
			mysqldump "$y" >"sqldb-$y.sql" 2>>"$LOGDIR/$LOGFILE"
	 	fi
	fi
	done

	tar cvvfz "$DEVICENAME-sql.tar.gz" *.sql 2>/dev/null >>"$LOGDIR/$LOGFILE"
	rm *.sql 2>/dev/null
fi

cd "$startdir"

#

