#!/bin/sh
#
# SBackup - rendszer
#
# Lokális gép mentése:
#
# - mentés hálózati meghajtóra
#

. "./sbackup-config"

if ping -c 1 -W 1 "$NETHOST" >>/dev/null; then
	#echo "$NETHOST" létezik
	mount -t cifs "//$NETHOST/$NETSHARE" "$NETTARGET" -o rw,username="$NETUSER",password="$NETPASSWORD" 2>>"$LOGDIR/$LOGFILE"

	if [ -d "$NETTARGET" ]; then
		d=`date`
		#cd $NETTARGET/$NETDIR
	else
		d=`date`
		#mkdir $NETTARGET 2>>/dev/null
	fi
	cp -r -u "$SYSTEMBACKUPDIR"/* "$NETTARGET/$NETDIR" 2>>"$LOGDIR/$LOGFILE"
	umount "$NETTARGET" 2>>"$LOGDIR/$LOGFILE"
else
	echo "$NETHOST" nem elérhető. 2>>"$LOGDIR/$LOGFILE"
fi

#
