#!/bin/bash
#
# SBackup - rendszer
#
# Lokális gép mentése
#

. "./sbackup-init"

d=`date`
echo "$d Mentés elkezdése." >> "$LOGDIR/$LOGFILE"

./sbackup-rclone-full
./sbackup-usb-copy-full
./sbackup-net-copy-full

echo $ENCODINGPASSPHARSE > $SYSTEMBACKUPDIR/$DEVICENAME.tar.gz

d=`date`
echo "$d Kész." >> "$LOGDIR/$LOGFILE"

#
