#!/bin/bash
#
# KVM virtuális gép
#
# virtuális gép kijelzője grafikus terminálon
#

localdir=`dirname $0`
. $localdir/../vm-config

if [ -z $1 ]; then
  vname="$DEFAULT_VM"
else
  vname=$1
fi

virt-viewer $vname &

#
