#!/bin/sh
#
# SysInfo - rendszer
#
# Modul: apache2
#

L_RUN="Webszerver (apache2) fut."
L_NORUN="Webszerver (apache2) nem fut."

ar=`ps auxw | grep apache2 | grep -v grep | grep -v www-data`

if [ -n "$ar" ]; then
	echo $L_RUN
else
	echo $L_NORUN
fi

#
