#!/bin/sh
#
# SysInfo - rendszer
#
# vezérlés
#

d=`dirname $0`
. $d/sysinfo-config

#cd $BINDIR

d=`date`
echo > $OUTPUTFILE
echo $d >> $OUTPUTFILE
echo >> $OUTPUTFILE

# rendszer
uname -a >> $OUTPUTFILE
fi=`uptime | awk {'print $3'} | sed -r 's/,/ /g'`
echo $L_UPTIME: $fi >> $OUTPUTFILE
echo >> $OUTPUTFILE

# processzor
m=`cat /proc/cpuinfo | grep "model name"`

cn=0
for i in $m; do
	if [ $i = "model" ]; then
		cn=$((cn+1))
	else
		if [ $i != "name" ] && [ $i != ":" ] && [ $cn = 1 ]; then
				pn=$pn" "$i
		fi
	fi
done

echo $L_PROCESSORNAME: $pn - $L_CORENUMBER: $cn >> $OUTPUTFILE

#echo >> $OUTPUTFILE

# terhelés
# 1 perc
#load=$(awk '{ print $1; }' < /proc/loadavg)
# 5 perc
load=$(awk '{ print $2; }' < /proc/loadavg)
# 15 perc
#load=$(awk '{ print $3; }' < /proc/loadavg)

t=`echo "$load * 100 / $cn" | bc`
echo $L_LOAD: $t % >> $OUTPUTFILE

echo >> $OUTPUTFILE

# memória

m=`cat /proc/meminfo | grep MemTotal | awk {'print $2'}`
m=$((m/1000/1000))

f=`cat /proc/meminfo | grep MemFree | awk {'print $2'}`
f=$((f/1000/1000))

echo $L_MEMORY: $m Gb - $L_MEMORYFREE: $f Gb >> $OUTPUTFILE

echo >> $OUTPUTFILE

# partíciók

d=` df -h --output=source,pcent,target -x tmpfs -x devtmpfs `

bifs=$IFS
IFS='
'
echo $L_PARTITIONS >> $OUTPUTFILE

k="x"
for i in $d; do
	if [ $k != "x" ]; then
		i=`echo $i | sed -r 's/  */ /g'`
		echo $i >> $OUTPUTFILE
	else
		k="q"
	fi
done
IFS=$bifs

echo >> $OUTPUTFILE

# process futásának ellenőrzése
echo $L_PROCESS >> $OUTPUTFILE

for i in $PROCESS; do
	ar=`ps auxw | grep $i | grep -v grep`
	if [ -n "$ar" ]; then
		echo - $i $L_RUN >> $OUTPUTFILE
	else
		echo - $i $L_NORUN >> $OUTPUTFILE
	fi
done

echo >> $OUTPUTFILE

# beépülő modulok

for i in $PLUGINS; do
	if [ -f $i ]; then
		echo $L_PLUGINSTART: $i >> $OUTPUTFILE
		. ./$i >> $OUTPUTFILE
		echo >> $OUTPUTFILE
	fi
done

#echo >> $OUTPUTFILE

if [ $SHOW_OUTPUTFILE = 1 ]; then
	cat $OUTPUTFILE
fi

#cd $TPATH

#
