#!/bin/sh
#
# SysInfo - rendszer
#
# Modul: apache2
#

L_RUN="SQL szerver (mariadb) fut."
L_NORUN="SQL szerver (mariadb) nemfut."

ar=`ps auxw | grep mariadb | grep -v grep | grep -v www-data`

if [ -n "$ar" ]; then
	echo $L_RUN
else
	echo $L_NORUN
fi

#
