#!/bin/sh

# Debian init script

### BEGIN INIT INFO
# Provides:
# Required-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:
# Default-Stop:
# Short-Description:
### END INIT INFO

DAEMON="./initsh"
PATH=/bin:/usr/bin:/sbin:/usr/sbin;/usr/local/bin

logger "Indítás: $DAEMON"

if [ -e /run/systemd/system ] ; then
    #exit 0
    echo >>/dev/null
fi

if [ ! -e $DAEMON ]; then
    exit 0
fi

startsh() {
  . /lib/lsb/init-functions
  verbose_log_action_msg() { [ "$VERBOSE" = no ] || log_action_msg "$@"; }

  #log_progress_msg "Folyamatban:" "$0"
  #log_end_msg 0
  #log_failure_msg "Hiba:" "$0"
  #log_end_msg 1

  case "$1" in
      start)
        log_action_begin_msg "Indítás:" "$0 "
        #start-stop-daemon --start --quiet --exec $DAEMON
        log_action_end_msg 0
        return 0
        ;;
      stop|restart|reload|force-reload)
        log_daemon_msg "Leállítás/újraindítás:" "$0"
        #start-stop-daemon --stop --quiet --exec $DAEMON
        log_end_msg 0
        return 0
        ;;
      show)
        log_daemon_msg "Információ:" "$0"
        log_end_msg 0
        return 0
        ;;
      *)
        log_success_msg "Használat: $0 {stop|reload|force-reload|show}"
        log_success_msg "           egyéb info"
        return 1
        ;;
  esac
}

startsh "$@"

#
