#!/bin/bash
#
# KVM virtuális gép
#
# hálózat állapota
#

localdir=`dirname $0`
. $localdir/../vm-config

if [ -z $1 ]; then
  vnet="$DEFAULT_NET"
else
  vnet=$1
fi

virsh net-list --all

virsh net-info $DEFAULT_NET
virsh net-dhcp-leases $DEFAULT_NET

#
