#!/bin/bash
#
# UPSShutDown
#
# Beállítások, konfiguráció
#

# indítási könyvtár
TPATH=`pwd`

# figyelt fájl
UPS_LISTEN_FILE="/etc/killpower"
UPS_CLIENT_LISTEN_FILE="/home/peter/killpower"

# adatok tárolója
LOGFILE="upsshtdwn.log"

# kilépéskor az adatok megjelenítése: 0 - nem, 1 - igen
SHOW_LOGFILE=1

# távoli gépek
REMOTE_MACHINES="192.168.16.122"

# távoli gépekhez felhasználó, jelszó
REMOTE_USER="peter"
REMOTE_PASSWORD=""
# ssh-keygen új kulcs páros létrehozása
# ssh-copy-id user@szerver folyamatos lefogadásra

# leállítás utasítás
SHUTDOWN_COMMAND="/sbin/shutdown -h +1"

# modulok
PLUGINS="upsshtdwn-m"

# a program helye
BINDIR="/usr/local/bin"

# e-mail küldése
REPORT_TO_MAIL=1
MAIL_TO="hidden@mail.com"
MAIL_FROM="hidden@mail.com"
MAIL_BCC=""

# nyelvi elemek - language
L_HOSTNAME="Szerver neve"
L_UPS_SERVER="A szerveren van szünetmentes."
L_UPS_NOSERVER="A szerveren nincs szünetmentes."
L_LISTEN_FILE_FOUND="A figyelt fájl létezik."
L_LISTEN_FILE_NOT_FOUND="A figyelt fájl nem létezik."
L_SHUTDOWN_START="A leállítás indítása..."
L_SHUTDOWN_TO_CLIENT="Jelzés küldése a távoli eszközöknek."
L_ACTION="A szünetmentesen nincs áram, a leállítás folyamatban."
L_NOACTION="Nincs teendő."
L_PLUGIN_START="Beépülő modul indítása:"
L_MAIL_SUBJECT="Szerver leállítás"
L_MAIL_TEXT="A szünetmentes leállítást kezdeményezett."
L_MAIL_ERROR="Hba a levélküldés során."
L_MAIL_OK="Értesítés elküldve."

#
