#!/bin/bash
#
# UPSShutDown
#
# E-mail küldés
# Szükséges: SSMTP
#

d=`dirname $0`
. $d/upsshtdwn-config

echo "To: $MAIL_TO" > "$MAILFILE"
echo "Bcc: $MAIL_BCC" >> "$MAILFILE"
echo "From: $MAIL_FROM" >> "$MAILFILE"
echo "MIME-Version: 1.0" >> "$MAILFILE"
echo "Content-Type: text/html; charset=utf-8" >> "$MAILFILE"
echo "Subject: $L_MAIL_SUBJECT" >> "$MAILFILE"
echo "<html>" >> "$MAILFILE"
echo "<head>" >> "$MAILFILE"
echo "<meta Content-Type: text/html; charset=utf-8>" >> "$MAILFILE"
echo "<head>" >> "$MAILFILE"
echo "<body>" >> "$MAILFILE"
echo "<br />" >> "$MAILFILE"
echo "$L_MAIL_TEXT" >> "$MAILFILE"
echo "<br />" >> "$MAILFILE"
echo "<br />" >> "$MAILFILE"

f=`cat $LOGFILE`
bifs=$IFS
IFS='
'
for i in $f; do
	echo "$i <br />" >> "$MAILFILE"
done
IFS=$bifs

echo "<br />" >> "$MAILFILE"
echo "</body>" >> "$MAILFILE"
echo "</html>" >> "$MAILFILE"

cat "$MAILFILE" | ssmtp $MAIL_TO >/dev/null 2>&1

if [ $? != 0 ]; then
	echo $L_MAIL_ERROR >>$LOGFILE
else
	echo $L_MAIL_OK >>$LOGFILE
fi

#
