#!/bin/bash
#
# video konvertálás
#
# felirat cseréje a megadottra

for i in *.mkv; do
	sub=${i%.*}.srt
	if [ -f $sub ]; then
		mkvsub $i $sub 2>/dev/null
	else
		echo "Hiányzó fájl. (  $sub )"
	fi
done

#
