#!/bin/bash
#
# video konvertálás
#
# felirat cseréje a megadottra

for i in *.mkv; do
	sub=${i%.*}.srt
	if [ -f "$sub" ]; then
        ffmpeg -i "$i" -sub_charenc 'UTF-8' -f srt -i "$sub" -map 0 -c:v copy -c:a copy -c:s srt "s$i" >/dev/null 2>/dev/null
	else
		echo "Hiányzó fájl. (  $sub )"
	fi
done

#
