#!/bin/bash
#
# KVM virtuális gép
#
# virtuális gépről adatok
#

localdir=`dirname $0`
. $localdir/../vm-config

if [ -z $1 ]; then
  vname="$DEFAULT_VM"
else
  vname=$1
fi

echo
virsh dominfo $vname

#
