#!/bin/bash
#
# KVM virtuális gép
#
# kilövés, ha a leállítás nem működik
#

localdir=`dirname $0`
. $localdir/../vm-config

if [ -z $1 ]; then
  vname="$DEFAULT_VM"
else
  vname=$1
fi

virsh dumpxml $vname > $vname.xml

#
