#!/bin/bash
#
# KVM virtuális gép
#
# virtuális gép memória
#

localdir=`dirname $0`
. $localdir/../vm-config

if [ -z $1 ]; then
  vname="$DEFAULT_VM"
else
  vname=$1
fi

if [ -z $2 ]; then
  mem="4096"
else
  mem=$2
fi

virsh setmaxmem $vname $mem --config
virsh setmem $vname $mem --config

#
