context.modules = [
    { name = "libpipewire-module-filter-chain"
        args = {
            node.name = "equalizer_sink"
            node.description = "EQ: magas hangok levágása"
            media.name = "EQ: magas hangok levágása"
            filter.graph = {
                nodes = [
                    {
                        type = ladspa
                        name = equalizer
                        plugin = mbeq_1197
                        label = mbeq
                        control = {
                            "31Hz" = 4.0
                            "62Hz" = 3.0
                            "125Hz" = 2.0
                            "250Hz" = 1.0
                            "500Hz" = 0.0
                            "1kHz" = 0.0
                            "2kHz" = -1.0
                            "4kHz" = -2.0
                            "8kHz" = -3.0
                            "16kHz" = -3.0
                        }
                    }
                ]
            }
            capture.props = {
                node.name = "input.equalizer"
                media.class = "Audio/Sink"
                audio.channels = 2
                audio.position = [ FL FR ]
                # Passzívvá tesszük, hogy ne tartsa ébren a rendszert
                node.passive = true
                node.always-process = false
            }
            playback.props = {
                node.name = "output.equalizer"
                audio.channels = 2
                audio.position = [ FL FR ]
                # Ha a kimenetre sincs kötve semmi, ez is elalszik
                node.passive = true
                node.always-process = false
            }
        }
    }
]
