context.modules = [
    { name = "libpipewire-module-filter-chain"
        args = {
            node.name = "bluetooth_bass"
            node.description = "EQ: magas hang levágás, basszus emelés"
            media.name = "EQ: magas hang levágás, basszus emelé"
            
            filter.graph = {
                nodes = [
                    {
                        type = ladspa
                        name = equalizer
                        plugin = mbeq_1197
                        label = mbeq
                        control = {
                            # Basszus kiemelése (Erőteljes mélyek)
                            "31Hz" = 5.0
                            "62Hz" = 5.0
                            "125Hz" = 3.0
                            
                            # Középhangok (Gyári értéken hagyva)
                            "250Hz" = 0.0
                            "500Hz" = 0.0
                            "1kHz" = 0.0
                            "2kHz" = 0.0
                            
                            # Magashangok vágása (Halkítás, hogy ne sziszegjen)
                            "4kHz" = -6.0
                            "8kHz" = -7.0
                            "16kHz" = -8.0
                        }
                    }
                ]
            }
            capture.props = {
                node.name = "effect_input.eq"
                media.class = "Audio/Sink"
                audio.channels = 2
                audio.position = [ FL FR ]
                node.passive = true
                node.always-process = false
                node.suspend-on-idle = 3
                session.suspend-on-idle = true
            }
            playback.props = {
                node.name = "effect_output.eq"
                audio.channels = 2
                audio.position = [ FL FR ]
                node.passive = true
                node.always-process = false
                node.suspend-on-idle = 3
                session.suspend-on-idle = true
            }
        }
    }
]