#!/bin/sh
#
# SFDaemon - rendszer
#
# daemon leállítása
#

d=`dirname $0`
. $d/sfdaemon-config

#cd $BINDIR

if [ $ENABLE_EXIT_CODE  != "0" ]; then
	echo $EXIT_CODE > $FILETOLISTEN
else
	if [ -f $PIDFILE ]; then
		pid=`cat $PIDFILE`
		kill -9 $pid 2>/dev/null
		rm $PIDFILE #2>/dev/null
	else
		pid=`ps -A | grep $SFDAEMON | awk '{print $1}'`
		kill -9 $pid 2>/dev/null
		#echo $pid
		#killall $SFDAEMON 2>/dev/null
	fi
fi

d=`date`
echo "$d Daemon leállítva." >> $LOGDIR/$LOGFILE

#cd $TPATH

#
