#!/bin/sh
#
# SFDaemon - rendszer
#
# daemon
#

d=`dirname $0`
. $d/sfdaemon-config

#cd $BINDIR

sd=`stat --printf=%Y $FILETOLISTEN`

al=true

while $al; do
	ld=`stat --printf=%Y $FILETOLISTEN`
	#echo $FILETOLISTEN $sd $ld
	if [ $ld != $sd ]; then
		if [ $ENABLE_EXIT_CODE  != "0" ]; then
			fv=`cat $FILETOLISTEN`
			if [ $fv = $EXIT_CODE ]; then
				al=false
				if [ -f $PIDFILE ]; then
					rm $PIDFILE #2>/dev/nul
				fi
			fi
		fi
		if $al; then
			#echo $sd $ld
			sd=$ld
			d=`date`
			echo "$d Program futtatása: $COMMAND" >> $LOGDIR/$LOGFILE
			if [ $ENABLE_MULTI_COMMAND != "0" ]; then
				comid=`cat $FILETOLISTEN`
				i=0
				for f in $COMMANDS; do
					if [ $i = $comid ]; then
						eval "$f";
					fi
					i=$((i+1))
				done
			else
				eval "$COMMAND";
			fi
		fi
	#else
		#echo eq
	fi
	sleep $SLEEPTIME
done

#cd $TPATH

#
