#!/bin/sh
#
# SFDaemon - rendszer
#
# daemon leállítása
#

d=`dirname $0`
. $d/sfdaemon-config

#cd $BINDIR

if [ -f $PIDFILE ]; then
	pid=`cat $PIDFILE`
	kill -9 $pid 2>/dev/null
	rm $PIDFILE #2>/dev/nul
else
	pid=`ps -A | grep $SFDAEMON | awk '{print $1}'`
	kill -9 $pid 2>/dev/null
	#echo $pid
	#killall $SFDAEMON 2>/dev/null

fi

d=`date`
echo "$d Daemon leállítva." >> $LOGDIR/$LOGFILE

#cd $TPATH

#
