#!/bin/sh
#
# SFDaemon - rendszer
#
# daemon indítása
#

d=`dirname $0`
. $d/sfdaemon-config

#cd $BINDIR

if [ -f $PIDFILE ]; then
	d=`date`
	echo "$d Daemon már fut." >> $LOGDIR/$LOGFILE
else
	d=`date`
	echo "$d Daemon indítása." >> $LOGDIR/$LOGFILE

	# log rotáció
	if [ $ENABLE_LOG = 1 ]; then
			d=`date`
			./backup-log 2>/dev/null
			echo "$d Log rotáció." >> $LOGDIR/$LOGFILE
	fi
	#echo $SFDAEMON
	./$SFDAEMON & echo $! > $PIDFILE

	d=`date`
	echo "$d Daemon fut." >> $LOGDIR/$LOGFILE
fi

#cd $TPATH

#
