#!/bin/bash
#
# Külső ip cím változás figyelése
#
# E-mail küldés
# Szükséges: SSMTP vagy MSMTP
#

d=`dirname $0`
. $d/ipm-config

echo "To: $MAIL_TO" > ./mail.txt
echo "Bcc: $MAIL_BCC" >> ./mail.txt
echo "From: $MAIL_FROM" >> ./mail.txt
echo "MIME-Version: 1.0" >> ./mail.txt
echo "Content-Type: text/html; charset=utf-8" >> ./mail.txt
echo "Subject: $L_MAIL_SUBJECT" >> ./mail.txt
echo "<html>" >> ./mail.txt
echo "<head>" >> ./mail.txt
echo "<meta Content-Type: text/html; charset=utf-8>" >> ./mail.txt
echo "<head>" >> ./mail.txt
echo "<body>" >> ./mail.txt
echo "<br />" >> ./mail.txt
echo "$L_MAIL_TEXT" >> ./mail.txt
echo "<br />" >> ./mail.txt
echo "<br />" >> ./mail.txt

f=`cat $LOGFILE`
bifs=$IFS
IFS='
'
for i in $f; do
	echo "$i <br />" >> ./mail.txt
done
IFS=$bifs

echo "<br />" >> ./mail.txt
echo "</body>" >> ./mail.txt
echo "</html>" >> ./mail.txt

#cat ./mail.txt | ssmtp $MAIL_TO >/dev/null 2>&1
cat ./mail.txt | usmtp $MAIL_TO >/dev/null 2>&1

if [ $? != 0 ]; then
	echo $L_MAIL_ERROR >>$LOGFILE
	echo >>$LOGFILE
else
	echo $L_MAIL_OK >>$LOGFILE
	echo >>$LOGFILE
fi

#
