#!/bin/bash

start() {
  /opt/startvm
}

stop() {
  /opt/stopvm
}

reload() {
  /opt/stopvm
  /opt/startvm
}



case $1 in
  start|stop|reload) "$1" ;;
esac

#


jogok, indítás
--------------

chmod 744 /etc/systemd/service/example.service
systemctl daemon-reload


indítás
-------

systemctl start example


automatikus indítás
-------------------

systemctl enable example
