#!/bin/bash

sudo -v

# paraméter
if [ $# -gt 0 ]; then
    sudo rm -f /var/lib/apt/lists/*_*
fi

sudo apt update
apt list --upgradable

read -r -p "[ENTER]" valasz

if [ -n "$valasz" ]; then
    exit 1
fi

sudo apt full-upgrade -y
sudo apt autoclean
sudo apt autoremove -y

#
