#!/bin/bash
#
# QBackup
#
# qbackup_clean
# Mentések törlése
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Beállítás fájl hiba."; exit 1; fi

# Log
echo ""
echo "== Tisztítás"
echo "$0"

# Ha "all" paramétert kap, mindent töröl, egyébként csak a régieket
if [ "$1" == "all" ]; then
    # Log
    echo "Az összes eddigi különbözeti mentés törlése..."
    if [ -d "$Q_BACKUP_DEST_OLD" ]; then
        rm -rf "$Q_BACKUP_DEST_OLD"
        echo
    fi
    mv "$Q_BACKUP_DEST" "$Q_BACKUP_DEST_OLD"
    mkdir -p "$Q_BACKUP_DEST"
    find "$Q_BACKUP_DEST_OLD" -mindepth 1 -maxdepth 1 -type f -name "*${Q_ARCHIV}*" | while read -r archiv_dir; do
        echo "$archiv_dir"
  		cp "$archiv_dir" "$Q_BACKUP_DEST"
    done
else
    echo "Régi különbözeti mentések törlése ($Q_KEEP_DAYS napnál régebbiek)..."
    if [ -d "$Q_BACKUP_DEST" ]; then
        find "$Q_BACKUP_DEST" -name "*_diff_*.tar.gz" -type f -mtime +"${Q_KEEP_DAYS}" -delete
    fi
fi

echo "== Tisztítás megtörtént"
echo ""

#

