#!/bin/bash
#
# QBackup
#
# qbackup_copy
# Mentések másolása egyéb helyi könyvtárakba vagy külső meghajtóra
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else exit 1; fi

# Log
echo ""
echo "=== Mentés másolása helyi mappákba"
echo "$0"
echo ""

# rclone ellenőrzése
if ! command -v rclone &> /dev/null; then
    echo "Hiba: Az 'rclone' nincs telepítve!"
    exit 1
fi

# Mentés ellenőrzése
if [ ! -d "$Q_BACKUP_DEST" ] || [ -z "$(ls -A "$Q_BACKUP_DEST")" ]; then
    echo "Figyelem: A helyi mentési mappa ($Q_BACKUP_DEST) üres vagy nem létezik. Kilépés."
    exit 0
fi

# Paraméter
if [ ! -z "$1" ]; then
    # USB mentés - rclone crypt
    echo "Titkosított rclone másolás indítása..."
    dir=`pwd`
    ( cd "$1" && rclone sync "$dir/$Q_BACKUP_DEST" "${Q_RCLONE_USB_CRYPT_REMOTE}:Mentés" --verbose )
    Q_RCLONE_STATUS=$?
else
    # Helyi mappákba másolás
    Q_RCLONE_STATUS=0
    for q_dest in "${Q_BACKUP_COPY_DESTS[@]}"; do
        echo "Szinkronizálás a következő helyre: $q_dest"
        rclone sync "$Q_BACKUP_DEST" "$q_dest" --verbose
        if [ $? -ne 0 ]; then Q_RCLONE_STATUS=1; fi
    done
fi

# Hiba kezelés
if [ $Q_RCLONE_STATUS -eq 0 ]; then
    echo "=== Másolás sikeresen végrehajtva."
else
    echo "=== [HIBA] A másolás során hiba történt!"
    exit 1
fi

# Log
echo "=== Másolás megtörtént"
echo ""

#
