#!/bin/bash
#
# QBackup
#
# qbackup_copy
# Mentések másolása egyéb helyi könyvtárakba vagy külső meghajtóra
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Beállítás fájl hiba."; exit 1; fi

# Log
echo ""
echo "=== Mentés másolása helyi mappákba"
echo "$0"
echo ""

# rclone ellenőrzése
if ! command -v rclone &> /dev/null; then
    echo "Hiba: Az 'rclone' nincs telepítve!"
    exit 1
fi

# Paraméter
if [ ! -z "$1" ]; then
    # Mentés ellenőrzése
    if [ ! -d "$Q_BACKUP_CRYPT_DEST" ] || [ -z "$(ls -A "$Q_BACKUP_CRYPT_DEST")" ]; then
        echo "Figyelem: A helyi mentési mappa ($Q_BACKUP_CRYPT_DEST) üres vagy nem létezik. Kilépés."
        exit 0
    fi
    # USB mentés - rclone crypt
    echo "Titkosított rclone másolás indítása..."
    #dir=`pwd`
    #cd "$1/$Q_BACKUP_CRYPT_DEST"
    #echo "$1/$Q_BACKUP_CRYPT_DEST"
    mkdir -p "$1/$Q_BACKUP_CRYPT_DEST"
    if [ -d "$1/$Q_BACKUP_CRYPT_DEST" ]; then
        rclone sync "$Q_BACKUP_CRYPT_DEST" "$1/$Q_BACKUP_CRYPT_DEST" --verbose
        Q_RCLONE_STATUS=$?
    fi
else
    # Mentés ellenőrzése
    if [ ! -d "$Q_BACKUP_DEST" ] || [ -z "$(ls -A "$Q_BACKUP_DEST")" ]; then
        echo "Figyelem: A helyi mentési mappa ($Q_BACKUP_DEST) üres vagy nem létezik. Kilépés."
        exit 0
    fi
    # Helyi mappákba másolás
    Q_RCLONE_STATUS=0
    for q_dest in "${Q_BACKUP_COPY_DESTS[@]}"; do
        mkdir -p "$q_dest"
        if [ -d "$q_dest" ]; then
            echo "Szinkronizálás a következő helyre: $q_dest"
            rclone sync "$Q_BACKUP_DEST" "$q_dest" --verbose
            if [ $? -ne 0 ]; then Q_RCLONE_STATUS=1; fi
        fi
    done
fi

# Hiba kezelés
if [ $Q_RCLONE_STATUS -eq 0 ]; then
    echo "=== Másolás sikeresen végrehajtva."
else
    echo "=== [HIBA] A másolás során hiba történt!"
    exit 1
fi

# Log
echo "=== Másolás megtörtént"
echo ""

#
