#!/bin/bash
#
# QBackup
#
# qbackup_archiv
# Archív mentés vezérlés - speciális könyvtárakból
#

DIR="$(pwd)"
# A szkript indítási mappája
SCRIPT_DIR=$(dirname "$BASH_SOURCE[0]")
cd "$SCRIPT_DIR"

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Beállítás fájl hiba."; cd "$DIR"; exit 1; fi

# Log
echo ""
echo "[$(date '+%Y-%m-%d %H:%M:%S')] qbackup_archiv archívum mentése elindult"
echo "$0"
echo ""

# Archiv mappák tömörítése
if [ -f "./qbackup_tar_archiv" ]; then
    bash ./qbackup_tar_archiv
else
    echo "Hiba: A qbackup_tar_archiv nem található!"
fi

# Elkészült fájlok ellenőrzése
if [ -f "./qbackup_check" ]; then
    bash ./qbackup_check
    #if [ $? -ne 0 ]; then
    #fi
fi

# Kódolás
if [ -f "./qbackup_crypt" ]; then
    bash ./qbackup_crypt
else
    echo "Hiba: A qbackup_crypt nem található!"
fi

# Log
echo "[$(date '+%Y-%m-%d %H:%M:%S')] qbackup_archiv archívum mentése megtörtént"
echo ""

cd "$DIR"

#

