#!/bin/bash
#
# QBackup
#
# qbackup_clean
# Mentések törlése
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else exit 1; fi

# Log
echo ""
echo "== Tisztítás"
echo "$0"

# Ha "all" paramétert kap, mindent töröl, egyébként csak a régieket
if [ "$1" == "all" ]; then
    # Log
    echo "Az összes eddigi különbözeti mentés törlése..."
    rm -f ${Q_BACKUP_DEST}/*_diff_*.tar.gz
    rm -f ${Q_SNAP_DIR}/*.snap
else
    echo "Régi különbözeti mentések törlése (${Q_KEEP_DAYS} napnál régebbiek)..."
    if [ -d "$Q_BACKUP_DEST" ]; then
        find "$Q_BACKUP_DEST" -name "*_diff_*.tar.gz" -type f -mtime +${Q_KEEP_DAYS} -delete
    fi
fi

echo "== Tisztítás megtörtént"
echo ""

#

