#!/bin/bash
#
# QBackup
#
# qbackup_rclone
# Mentések szinkronizálása felhőbe rclone segítségével
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Beállítás fájl hiba."; exit 1; fi

# Log
echo ""
echo "=== Felhőbe (rclone) mentés"
echo $0
echo ""

# rclone ellenőrése
if ! command -v rclone &> /dev/null; then
    echo "Hiba: Az 'rclone' nem található!"
    exit 1
fi

# Mentési mappa ellenőrzése
if [ ! -d "$Q_BACKUP_DEST" ] || [ -z "$(ls -A "$Q_BACKUP_DEST")" ]; then
    echo "A helyi mentési mappa ($Q_BACKUP_DEST) üres vagy nem létezik."
    exit 0
fi

echo "Szinkronizálás folyamatban: $Q_BACKUP_DEST  =>  ${Q_RCLONE_REMOTE}:${Q_RCLONE_DEST_DIR}"

# Szinkronizálás indítása
# A --update - a felhőben lévő újabb fájlokat ne írja felül
# A --verbose (-v) - állapot kiírása
rclone sync "$Q_BACKUP_DEST" "${Q_RCLONE_REMOTE}:${Q_RCLONE_DEST_DIR}" --verbose

if [ $? -eq 0 ]; then
    echo "=== A felhőbe szinkronizálásmegtörtént"
else
    echo "Hiba: Az rclone szinkronizálás során hiba történt!"
    exit 1
fi

echo ""

#

