#!/bin/bash
#
# QBackup
#
# qbackup_restore_full
# Minden mentés kicsomagolása
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else exit 1; fi

# Mappa ellenőrzés
mkdir -p "$Q_RESTORE_DEST"

# Log
echo ""
echo "=== Minden mentés visszaállítása"
echo $0
echo ""

# Rendszer
for dir in "${Q_BACKUP_SYSTEM[@]}"; do
    name=$(basename "$dir")
    full_tar="${Q_BACKUP_DEST}/full_system_${name}.tar.gz"

    if [ -f "$full_tar" ]; then
        echo "${name}..."
        tar -xzf "$full_tar" -C "$Q_RESTORE_DEST"

        # Különbözeti mentések
        for diff_tar in $(ls -v ${Q_BACKUP_DEST}/*_diff_system_${name}.tar.gz 2>/dev/null); do
            echo "Különbözeti mentés kicsomagolása $(basename $diff_tar)..."
            tar -xzf "$diff_tar" -C "$Q_RESTORE_DEST"
        done
    else
        echo "Nem található teljes mentés ${name}"
    fi
done

# home mappa visszaállítása
for user_dir in /home/*; do
    if [ -d "$user_dir" ]; then
        user_name=$(basename "$user_dir")
        for sub_dir in "${Q_BACKUP_HOME_SUBDIRS[@]}"; do
            full_tar="${Q_BACKUP_DEST}/full_home_${user_name}_${sub_dir}.tar.gz"

            if [ -f "$full_tar" ]; then
                echo "Kicsomagolás: home_${user_name}_${sub_dir}..."
                tar -xzf "$full_tar" -C "$Q_RESTORE_DEST"

                # Különbözeti mentések
                for diff_tar in $(ls -v ${Q_BACKUP_DEST}/*_diff_home_${user_name}_${sub_dir}.tar.gz 2>/dev/null); do
                    echo "Különbözet mentés kicsomagolása $(basename $diff_tar)..."
                    tar -xzf "$diff_tar" -C "$Q_RESTORE_DEST"
                done
            fi
        done
    fi
done

echo "=== Visszaállítás megtörtént"
echo ""

#

