#!/bin/bash
#
# QBackup
#
# qbackup_archiv
# Archív mentés vezérlés - speciális könyvtárakból
#

DIR="$(pwd)"
# A szkript indítási mappája
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
cd ${SCRIPT_DIR}

# Konfiguráció beolvasása
if [ -f "./qconfig" ]; then
    source ./qconfig
else
    echo "Hiba: A qconfig nem található a fő szkript mellett!"
    cd ${DIR}
    exit 1
fi

# Log
echo ""
echo "[$(date '+%Y-%m-%d %H:%M:%S')] qbackup_archiv archívum mentése elindult"
echo "$0"
echo ""

# Archiv mappák tömörítése
if [ -f "./qbackup_tar_archiv" ]; then
    bash ./qbackup_tar_archiv
else
    echo "Hiba: A qbackup_tar_archiv nem található!"
fi

# Elkészült fájlok ellenőrzése
if [ -f "./qbackup_check" ]; then
    bash ./qbackup_check
    #if [ $? -ne 0 ]; then
    #fi
fi

# Log
echo "[$(date '+%Y-%m-%d %H:%M:%S')] qbackup_archiv archívum mentése megtörtént"
echo ""

cd ${DIR}

#

