#!/bin/bash
#
# QBackup
#
# qbackup_copy_usb
# Mentések másolása külső meghajtóra
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else exit 1; fi

# Log
echo ""
echo "=== Külső eszköz keresése és mentés"
echo "$0"
echo ""

# Jogosultság ellenőrzése (root)
if [ "$EUID" -ne 0 ]; then
    echo "Hiba: Nincs jogosultság a meghajtók csatolásához! (root)"
    exit 1
fi

# Létrehozzuk az ideiglenes csatolási pontot, ha nincs
mkdir -p "$Q_USB_MOUNT_POINT"

# Külső meghajtók keresés
Q_PARTITIONS=$(lsblk -lnpo NAME,TYPE | grep -E 'part|rom' | awk '{print $1}')

Q_USB_FOUND=false

for q_part in $Q_PARTITIONS; do
    # ha már fel vannak csatolva valahova
    if mountpoint -q "$q_part" 2>/dev/null || grep -q "$q_part" /proc/mounts; then
        continue
    fi

    echo "Eszköz elérése: $q_part..."

    # Felcsatolás
    if mount "$q_part" "$Q_USB_MOUNT_POINT" 2>/dev/null; then

        # Ellenőrizzük, hogy ott van-e a jelzőfájl az USB gyökerében
        if [ -f "${Q_USB_MOUNT_POINT}/${Q_USB_MARKER_FILE}" ]; then
            echo "Biztonságos mentés: $q_part"
            Q_USB_FOUND=true

            # A mentés pontos helye
            #Q_USB_TARGET_DIR="${Q_USB_MOUNT_POINT}/qbackup"
            #mkdir -p "$Q_USB_TARGET_DIR"

            # qbackup_copy imndítása a célmappa átadásával
            if [ -f "./qbackup_copy" ]; then
                bash ./qbackup_copy "$Q_USB_TARGET_DIR"
            else
                echo "Hiba: A qbackup_copy modul nem található!"
            fi
        fi

        # Lecsatolás
        umount "$Q_USB_MOUNT_POINT"
        echo "Eszköz lecsatolva: $q_part"
    fi
done

# Csatolási pont törlése
rmdir "$Q_USB_MOUNT_POINT"

if [ "$Q_USB_FOUND" = false ]; then
    echo "'$Q_USB_MARKER_FILE' fájl nem található."
fi

echo "=== Külső mentés megtörtént"
echo ""

#

