#!/bin/bash
#
# QBackup
#
# qbackup
# Különbözeti mentés vezérlés
#

# A szkript indítási mappája
DIR="$(pwd)"
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
cd ${SCRIPT_DIR}
#echo $SCRIPT_NAME

# Konfiguráció beolvasása
if [ -f "./qconfig" ]; then
    source ./qconfig
else
    echo "Hiba: A qconfig nem található a fő szkript mellett!"
    cd ${DIR}
    exit 1
fi

# Log
echo ""
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Különbözeti mentés elindult"
echo "$0"
echo ""

# 1.
# Tömörítés
if [ -f "./qbackup_tar" ]; then
    bash ./qbackup_tar
else
    echo "Hiba: A qbackup_tar nem található!"
fi

# 2.
# Fájlok ellenőrzésa a másolások előtt
if [ -f "./qbackup_check" ]; then
    bash ./qbackup_check
    # Hibás fájlok
    if [ $? -ne 0 ]; then
        cd ${DIR}
        exit 1
    fi
fi

# 3.
# Mariadb mentés
if [ -f "./qbackup_mariadb" ]; then
    bash ./qbackup_mariadb
else
    echo "Hiba: A qbackup_mariadb nem található!"
fi

# 4.
# Kódolás
if [ -f "./qbackup_crypt" ]; then
    bash ./qbackup_crypt
else
    echo "Hiba: A qbackup_crypt nem található!"
fi

# 5.
# Rclone modul futtatása - felhős másolat készítése
if [ -f "./qbackup_rclone" ]; then
    bash ./qbackup_rclone
else
    echo "Hiba: A qbackup_rclone nem található!"
fi

# 6.
# Copy modul futtatása - helyi másolatok készítése
if [ -f "./qbackup_copy" ]; then
    bash ./qbackup_copy
else
    echo "Hiba: A qbackup_copy nem található!"
fi

# 7.
# Copy modul futtatása - felhasználó felmappelt külső eszközeinek keresése
if [ -f "./qbackup_copy_dir" ]; then
    bash ./qbackup_copy_dir
else
    echo "Hiba: A qbackup_copy_dir nem található!"
fi

# 8.
# Copy USB modul - külső hardver mentés
if [ -f "./qbackup_copy_usb" ]; then
    bash ./qbackup_copy_usb
else
    echo "Hiba: A qbackup_copy_usb nem található!"
fi

# Log
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Különbözeti mentés megtörtént"
echo ""

cd ${DIR}

#

