#!/bin/bash
# qbackup - Fő vezérlő szkript

DIR="$(pwd)"
# Megkeressük a szkript saját, valódi mappáját
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
cd ${SCRIPT_DIR}

# Konfiguráció beolvasása
if [ -f "./qconfig" ]; then
    source ./qconfig
else
    echo "Hiba: A qconfig nem található a fő szkript mellett!"
    cd ${DIR}
    exit 1
fi

# Log törlése
rm /var/log/qbackup.log

# Log beállítás
if [ "$LOG_SCREEN" = "1" ]; then
    exec > /var/log/qbackup.log 2>&1
else
    exec > >(tee -a /var/log/qbackup.log) 2>&1
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] qbackup elindítva."

# Modul futtatása
if [ -f "./qbackup_tar_full" ]; then
    bash ./qbackup_tar_full
else
    echo "Hiba: A qbackup_tar_full nem található!"
fi

# Ellenőrzés a másolások előtt
if [ -f "./qbackup_check" ]; then
    bash ./qbackup_check
    if [ $? -ne 0 ]; then
        echo ""
        echo "=================================="
        echo ""
        echo "A mentés sérült, a szinkronizálási folyamatok biztonsági okokból leállítva!"
        echo ""
        echo "=================================="
        echo ""
    fi
fi

# Mariadb mentés teljes
if [ -f "./qbackup_mariadb" ]; then
    bash ./qbackup_mariadb full
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] qbackup_full TELJES mentés sikeresen lefutott."

cd ${DIR}

#
