#!/bin/bash
#
# QBackup
#
# qbackup_mariadb
# MariaDB/MySQL adatbázisok mentése
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Konfigfájl hiba."; exit 1; fi

# Log
echo ""
echo "=== Mariadb adatbázisok mentése"
echo $0
echo ""

# db dump elérése
if command -v mariadb-dump &> /dev/null; then
    Q_DUMP_CMD="mariadb-dump"
elif command -v mysqldump &> /dev/null; then
    Q_DUMP_CMD="mysqldump"
else
    echo "Hiba: adatbázis mentéshez program nem található!"
    exit 1
fi

# Paraméter alapján mentés típus
if [ "$1" == "full" ]; then
    # Teljes mentés esetén fix név
    Q_FINAL_TAR="${Q_BACKUP_DEST}/full_mariadb_all_databases.tar.gz"
    echo "Típus: Teljes mentés (felülírással)"
else
    # Napi mentés esetén dátummal ellátott név
    DATE=$(date +%F)
    Q_FINAL_TAR="${Q_BACKUP_DEST}/${DATE}_diff_mariadb_all_databases.tar.gz"
    echo "Típus: Napi mentés (időzített)"
fi

# Ideiglenes tiszta .sql fájl helye
Q_TMP_SQL="/tmp/all_databases_dump.sql"

# DB-ből adatok mentése
echo "Adatbázisok exportálása..."
if [ "$Q_DB_PASS" == "" ]; then
    $Q_DUMP_CMD -u "$Q_DB_USER" --all-databases --single-transaction --quick --lock-tables=false > "$Q_TMP_SQL"
else
    $Q_DUMP_CMD -u "$Q_DB_USER" -p"$Q_DB_PASS" --all-databases --single-transaction --quick --lock-tables=false > "$Q_TMP_SQL"
fi

# Tömörítés
if [ $? -eq 0 ]; then
    echo "Tömörítés és mentés a célmappába..."
    tar -czf "$Q_FINAL_TAR" -C /tmp "$(basename "$Q_TMP_SQL")"

    # Kitakarítjuk a felesleges ideiglenes fájlt a /tmp-ből
    rm -f "$Q_TMP_SQL"
    echo "Az adatbázisok mentése megtörtént."
else
    echo "Az adatbázisok mentése hibás."
    rm -f "$Q_TMP_SQL"
    exit 1
fi

# Log
echo "=== Mariadb mentés megtörtént"
echo ""

#

