#!/bin/bash
#
# QBackup
#
# qbackup_tar_full
# Teljes mentés készítése
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Konfigfájl hiba."; exit 1; fi

# Különbözeti mentések törlése
if [ -f "./qbackup_clean" ]; then
    bash ./qbackup_clean all
fi

# Mappák létrehozása
mkdir -p "$Q_BACKUP_DEST" "$Q_SNAP_DIR"

# Kizárások kapcsolóinak összeállítása
Q_TAR_EXCLUDES=()
for exc in "${Q_EXCLUDES[@]}"; do
    Q_TAR_EXCLUDES+=("--exclude=$exc")
done

# Log
echo ""
echo "=== Teljes mentés indítása"
echo $0
echo ""

# Rendszer
for dir in "${Q_BACKUP_SYSTEM[@]}"; do
    if [ -d "$dir" ]; then
        name=$(basename "$dir")
        echo "Teljes mentés: full_system_${name}"
        rm -f "${Q_SNAP_DIR}/system_${name}.snap"
        tar "${Q_TAR_EXCLUDES[@]}" -czg "${Q_SNAP_DIR}/system_${name}.snap" -f "${Q_BACKUP_DEST}/full_system_${name}.tar.gz" "$dir"
    fi
done

# Felhasználók
for user_dir in /home/*; do
    if [ -d "$user_dir" ]; then
        user_name=$(basename "$user_dir")
        for sub_dir in "${Q_BACKUP_HOME_SUBDIRS[@]}"; do
            full_path="${user_dir}/${sub_dir}"
            if [ -d "$full_path" ]; then
                echo "Teljes mentés: full_home_${user_name}_${sub_dir}"
                rm -f "${Q_SNAP_DIR}/home_${user_name}_${sub_dir}.snap"
                tar "${Q_TAR_EXCLUDES[@]}" -czg "${Q_SNAP_DIR}/home_${user_name}_${sub_dir}.snap" -f "${Q_BACKUP_DEST}/full_home_${user_name}_${sub_dir}.tar.gz" "$full_path"
            fi
        done
    fi
done

echo "=== Teljes mentés megtörtént"
echo ""

#

