#!/bin/bash
#
# QBackup
#
# qbackup_restore_from_file
# Mentésekből visszaállítás
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else exit 1; fi

# Paraméterek ellenőrzése
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Használat: $0 <mentés_fájl_neve.tar.gz> <keresett_elem>"
    exit 1
fi

Q_TARGET_ARCHIVE="$1"
Q_SEARCH_TERM="$2"

# Megadott mentés ellenőrzése
if [ ! -f "${Q_BACKUP_DEST}/${Q_TARGET_ARCHIVE}" ] && [ ! -f "$Q_TARGET_ARCHIVE" ]; then
    echo "Hiba: A megadott mentési fájl nem található: $Q_TARGET_ARCHIVE"
    exit 1
fi

# Ha csak a fájlnevet adta meg a user, kiegészítjük a backup mappával
if [ -f "${Q_BACKUP_DEST}/${Q_TARGET_ARCHIVE}" ]; then
    Q_ARCHIVE_PATH="${Q_BACKUP_DEST}/${Q_TARGET_ARCHIVE}"
else
    Q_ARCHIVE_PATH="$Q_TARGET_ARCHIVE"
fi

# Mappa létrehozása
mkdir -p "$Q_RESTORE_DEST"

# Log
echo ""
echo "=== Visszaállítás indítása: "$Q_ARCHIVE_PATH""
echo $0
echo ""

# Pontos belső útvonal
Q_MATCHING_FILES=$(tar -tzf "$Q_ARCHIVE_PATH" 2>/dev/null | grep -i "$Q_SEARCH_TERM")

if [ -z "$Q_MATCHING_FILES" ]; then
    echo "'${SEARCH_TERM}' nem található a mentésben"
    exit 1
fi

# Mentés típus
filename=$(basename "$Q_ARCHIVE_PATH")

# Kicsomagolás
while read -r Q_FULL_PATH; do
    # Üres sor, kilépés
    [ -z "$Q_FULL_PATH" ] && continue

    echo "Talált útvonal: $Q_FULL_PATH"

    if [[ "$filename" == *"_diff_"* ]]; then
        # Különbözeti mentés
        base_name=$(echo "$filename" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}_diff_//')
        full_archive_path="${Q_BACKUP_DEST}/full_${base_name}"

        if [ -f "$full_archive_path" ]; then
            echo "- Kicsomagolás a teljes mentésből ($(basename "$full_archive_path"))..."
            ( cd "$Q_RESTORE_DEST" && tar -xzf "../$full_archive_path" "$Q_FULL_PATH" -C "$Q_RESTORE_DEST" 2>/dev/null )

            echo "- Keresés a különbözeti mentésekben ($filename)..."
            ( cd "$Q_RESTORE_DEST" && tar -xzf "../$Q_ARCHIVE_PATH" "$Q_FULL_PATH" -C "$Q_RESTORE_DEST" 2>/dev/null )
        else
            echo "Nincs teljes mentés (${full_archive_path})"
            ( cd "$Q_RESTORE_DEST" && tar -xzf "../$Q_ARCHIVE_PATH" "$Q_FULL_PATH" -C "$Q_RESTORE_DEST" 2>/dev/null )
        fi
    else
        # Teljes mentés
        echo "- Kicsomagolás a teljes mentésből..."
        ( cd "$Q_RESTORE_DEST" && tar -xzf "../$Q_ARCHIVE_PATH" "$Q_FULL_PATH" -C "$Q_RESTORE_DEST" )
    fi
done <<< "$Q_MATCHING_FILES"


echo "=== Visszaállítás megtörtént"
echo ""

#

