#!/bin/bash
#
# QBackup
#
# qbackup_full
# Teljes mentés
#

# Indítási mappa
DIR="$(pwd)"
# Megkeressük a szkript saját, valódi mappáját
SCRIPT_DIR=$(dirname "$BASH_SOURCE[0]")
cd "$SCRIPT_DIR"

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Beállítás fájl hiba."; cd "$DIR"; exit 1; fi

# Log
echo ""
echo "[$(date '+%Y-%m-%d %H:%M:%S')] qbackup_full teljes mentés elindítva"
echo $0
echo ""

# 1. Teljes mentés futtatása
if [ -f "./qbackup_tar_full" ]; then
    bash ./qbackup_tar_full
else
    echo "Hiba: A qbackup_tar_full nem található!"
fi

# 2. Ellenőrzés
if [ -f "./qbackup_check" ]; then
    bash ./qbackup_check
    if [ $? -ne 0 ]; then
        cd "$DIR"
        exit 1
    fi
fi

# 3.
# Mariadb mentés
if [ -f "./qbackup_mariadb" ]; then
    bash ./qbackup_mariadb full
else
    echo "Hiba: A qbackup_mariadb nem található!"
fi

# 4.
# Kódolás
if [ -f "./qbackup_crypt" ]; then
    bash ./qbackup_crypt
else
    echo "Hiba: A qbackup_crypt nem található!"
fi

# 5.
# Rclone modul futtatása - felhős másolat készítése
if [ -f "./qbackup_rclone" ]; then
    bash ./qbackup_rclone
else
    echo "Hiba: A qbackup_rclone nem található!"
fi

# 6.
# Copy modul futtatása - helyi másolatok készítése
if [ -f "./qbackup_copy" ]; then
    bash ./qbackup_copy
else
    echo "Hiba: A qbackup_copy nem található!"
fi

# 7.
# Copy modul futtatása - felhasználó felmappelt külső eszközének keresése
if [ -f "./qbackup_copy_dir" ]; then
    bash ./qbackup_copy_dir
else
    echo "Hiba: A qbackup_copy_dir nem található!"
fi

# 8.
# Copy USB modul - külső hardver mentés
if [ -f "./qbackup_copy_usb" ]; then
    bash ./qbackup_copy_usb
else
    echo "Hiba: A qbackup_copy_usb nem található!"
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] teljes mentés megtörtént"
echo ""

cd "$DIR"

#

