#!/bin/bash
#
# QBackup
#
# qbackup_tar_archiv
# Teljes emntés az archívumokról
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Konfigfájl hiba."; exit 1; fi

# Mappa beállítás ellenőrzése
if [ -z "$Q_ARCHIV" ]; then
    echo "A Q_ARCHIV változó üres a qconfig-ban!" >&2
    exit 1
fi

# Mappák létrehozása
mkdir -p "$Q_BACKUP_DEST" "$Q_SNAP_DIR"

# Log
echo ""
echo "=== Teljes archív mentés indítása"
echo $0
echo ""

# Felhasználók
for user_dir in /home/*; do
    if [ -d "$user_dir" ]; then
        user_name=$(basename "$user_dir")
        for sub_dir in "${Q_BACKUP_HOME_SUBDIRS[@]}"; do
            full_path="${user_dir}/${sub_dir}"
            if [ -d "$full_path" ]; then
                find "$full_path" -mindepth 1 -maxdepth 1 -type d -name "$Q_ARCHIV" | while read -r archiv_dir; do

                    echo "Teljes mentés: full_home_${user_name}_${sub_dir}_${Q_ARCHIV}"

                    rm -f "${Q_SNAP_DIR}/home_${user_name}_${sub_dir}_${Q_ARCHIV}.snap"

                    tar -czg "${Q_SNAP_DIR}/home_${user_name}_${sub_dir}_${Q_ARCHIV}.snap" -f "${Q_BACKUP_DEST}/full_home_${user_name}_${sub_dir}_${Q_ARCHIV}.tar.gz" "$archiv_dir"
                done
            fi
        done
    fi
done

echo "=== Teljes archív mentés megtörtént"
echo ""

#

