#!/bin/bash
# qbackup_tar_full - Teljes mentés készítése kizárásokkal

if [ -f "./qconfig" ]; then source "./qconfig"; else exit 1; fi

# Ellenőrizzük, hogy a változó nem üres-e, nehogy mindent kitoroljon/mentsen
if [ -z "$ARCHIV" ]; then
    echo "Hiba: Az ARCHIV változó üres a qconfig-ban!" >&2
    exit 1
fi

mkdir -p "$BACKUP_DEST" "$SNAP_DIR"

echo "=== TELJES MENTÉS INDÍTÁSA ==="

# Felhasználók $ARCHIV mappáinak teljes mentése
for user_dir in /home/*; do
    if [ -d "$user_dir" ]; then
        user_name=$(basename "$user_dir")
        for sub_dir in "${BACKUP_HOME_SUBDIRS[@]}"; do
            full_path="${user_dir}/${sub_dir}"
            if [ -d "$full_path" ]; then

                # Megkeressük a sub_dir-en belüli, $ARCHIV nevű mappát
                find "$full_path" -mindepth 1 -maxdepth 1 -type d -name "$ARCHIV" | while read -r archiv_dir; do

                    echo "Teljes mentés: full_home_${user_name}_${sub_dir}_${ARCHIV}"

                    rm -f "${SNAP_DIR}/home_${user_name}_${sub_dir}_${ARCHIV}.snap"

                    tar -czg "${SNAP_DIR}/home_${user_name}_${sub_dir}_${ARCHIV}.snap" -f "${BACKUP_DEST}/full_home_${user_name}_${sub_dir}_${ARCHIV}.tar.gz" "$archiv_dir"
                done
            fi
        done
    fi
done

echo "=== TELJES MENTÉS KÉSZ ==="

#
