#!/bin/bash
#
# QBackup
#
# qbackup_check
# Mentési archívumok integritásának és épségének ellenőrzése
#

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else exit 1; fi

# Log
echo ""
echo "=== Mentések épségének ellenőrzése (integritás teszt)"
echo "$0"
echo ""

# Mentési mappa ellenőrzés
if [ ! -d "$Q_BACKUP_DEST" ] || [ -z "$(ls -A "$Q_BACKUP_DEST")" ]; then
    echo "Figyelem: A mentési mappa ($Q_BACKUP_DEST) üres vagy nem létezik. Kilépés."
    exit 0
fi

Q_TOTAL_FILES=0
Q_CORRUPTED_FILES=0
Q_FAILED_LIST=()

# Ak az összes tar.gz fájl a mappából
mapfile -t Q_ARCHIVES < <(find "$Q_BACKUP_DEST" -maxdepth 1 -name "*.tar.gz" -type f)

#
for q_archive in "${Q_ARCHIVES[@]}"; do
    q_filename=$(basename "$q_archive")
    ((TOTAL_FILES++))
    echo -n "Tesztelés: $q_filename ... "
    # A tar -tf parancs végigolvassa a fájlt
    tar -tzf "$q_archive" > /dev/null 2>&1
    #Kilépési statusz ellenőrzése (hiba történt-e)
    if [ $? -eq 0 ]; then
        echo "[+]"
    else
        echo "[-] Sérült fájl."
        ((Q_CORRUPTED_FILES++))
        Q_FAILED_LIST+=("$q_filename")
    fi
done

#Log
echo ""
echo "=== Ellenőrzés vége"
echo "Összesen vizsgált fájl: $Q_TOTAL_FILES"

if [ "$Q_CORRUPTED_FILES" -eq 0 ]; then
    echo "Eredmény: Minden mentés rendben."
    exit 0
else
    echo "Eredmény: Sérült fájlok! ($Q_CORRUPTED_FILES db)"
    echo "A sérült fájlok listája:"
    for q_failed in "${Q_FAILED_LIST[@]}"; do
        echo "  - $q_failed"
    done
    exit 1
fi
echo ""

#

