#!/bin/bash
#
# QBackup
#
# qconfig
# Konfigurációs fájl a qbackup rendszerhez
#

# Log kiírása képernyőre is (1 ha megjelenjen)
Q_LOG_SCREEN="0"

# Log fájl
Q_LOG_FILE="qbackup.log"

# Rendszer könyvtárak mentés
Q_BACKUP_SYSTEM=("/etc"
                 "/var/www/html"
                 )

# A home könyvtárban felhasználói alkönyvtárak mentése
Q_BACKUP_HOME_SUBDIRS=("Dokumentumok"
                       "public_html"
                       "Projektek"
                       "Asztal"
                       )

# Mentések célmappája
Q_BACKUP_DEST="./backup"

# Kizárásk: ezeket a mintákat/mappákat hagyja ki a tar
Q_EXCLUDES=("backup"
            "_"
            "*.tmp"
            ".cache"
            )

# Archívum mappa külön archív mentéshez
Q_ARCHIV=("_"
          )

# Hány napig tartsuk meg a különbözeti (diff) mentéseket
Q_KEEP_DAYS=7

# Tar snapshot fájlok helye
Q_SNAP_DIR="./backup/snapshots"

# Helyreállítási célkönyvtár
Q_RESTORE_DEST="./restore"

# Az rclone config-ban megadott titkosított profil neve
# crypt típust választani, mappát megadni, jelszavakat megadni
Q_RCLONE_USB_CRYPT_REMOTE="usb_secret"

# Visszaállítás: felcsatolni az USB-t, majd rclone config-ban az út a felcsatolt mappa
# rclone sync "usb_titkos:" "./restore" --verbose

# Rclone távoli tárhely neve (elkészítve 'rclone config' paranccsal)
Q_RCLONE_REMOTE="gdrive"

# A mappa neve a felhőben
Q_RCLONE_DEST_DIR="Mentés"

# Helyi könyvtár útvonalak, ahová másolatot kerül
Q_BACKUP_COPY_DESTS=("/tmp/teszt_masolat-0"
                     "/tmp/teszt_masolat-1"
                     )

# Az USB-n keresendő jelzőfájl neve
Q_USB_MARKER_FILE=".backupusb"

# Ideiglenes csatolási pont az USB-knek
Q_USB_MOUNT_POINT="/mnt/qbackup_usb"

# MariaDB / MySQL hozzáférések
Q_DB_USER="root"
Q_DB_PASS=""

#

