#!/bin/bash
#
# QBackup
#
# starter
# Indító
#

# A szkript indítási mappája
DIR="$(pwd)"
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
cd ${SCRIPT_DIR}
#echo $SCRIPT_NAME

# Konfiguráció betöltése
if [ -f "./qconfig" ]; then source "./qconfig"; else echo "Beállítás fájl hiba."; cd $DIR; exit 1; fi

# Log törlése
if [ "$2" == "1" ]; then
    rm "$Q_LOG_FILE"
fi
if [[ "$1" == *"full"* ]]; then
    rm "$Q_LOG_FILE"
fi

# Paraméter
if [ -z "$1" ]; then
    cmd="qbackup"
else
    cmd=$1
fi

# Indítás, log-ok kezelésével
if [ -f "./$cmd" ]; then
    if [ "$Q_LOG_SCREEN" = "1" ]; then
        bash "./$cmd" 2>&1 | tee -a "$Q_LOG_FILE"
    else
        bash "./$cmd" >> "$Q_LOG_FILE" 2>&1
    fi
fi

cd ${DIR}

#

