#!/bin/bash
#
# QBackup
#
# starter_sync
# Indító
#

# A szkript indítási mappája
DIR="$(pwd)"
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
cd ${SCRIPT_DIR}

bash ./starter qbackup_sync_dirs

cd ${DIR}

#
