#!/bin/bash
#
# NetChk
#
# Beállítások, konfiguráció
#

# indítási könyvtár
TPATH=`pwd`

# log
LOGFILE="netchk.log"

# levélfájl
MAILFILE="netchkmail.txt"

# html levél: 0 - nem, 1 - igen
HTMLMAIL=1

# kilépéskor az adatok megjelenítése: 0 - nem, 1 - igen
SHOW_LOGFILE=1

# távoli gépek
REMOTE_MACHINES="192.168.16.200 192.168.16.201"

# várakozás másodpercben
SLEEPTIME=300

# leállítás utasítás
SHUTDOWN_COMMAND="/sbin/shutdown -h +1"

# modulok
PLUGINS=""

# e-mail küldése
REPORT_TO_MAIL=1
MAIL_TO="hidden@mail.com"
MAIL_FROM="hidden@mail.com"
MAIL_BCC=""

# nyelvi elemek - language
L_HOSTNAME="Szerver neve"
L_CHK_REMOTE="Távoli eszközök ellenőrzése..."
L_WAITING="Várakozás és újratesztelés..."
L_SHUTDOWN_START="A leállítás indítása..."
L_ACTION="A szünetmentesen nincs áram, a leállítás folyamatban."
L_NOACTION="Nincs teendő."
L_PLUGIN_START="Beépülő modul indítása:"
L_MAIL_SUBJECT="Szerver leállítás"
L_MAIL_TEXT="A szünetmentes leállítást kezdeményezett."
L_MAIL_ERROR="Hba a levélküldés során."
L_MAIL_OK="Értesítés elküldve."

#
